### ISSUE TITLE
remove Twitter and Facebook links from the episode Webpages

### ISSUE THREAD

**Issue by arminomoradio** [albertobeta/PodcastGenerator#101]
Hello,
i have a podcast private with friends.
I want to disable on the Episode page the Twitter and Facebook Links.
How can i remove the Twitter and Facebook links?
Regards
Armin Moradi

**Comment by kolumbus120** [comment]
Hi,
in the setting you have: "Podcast Generator Configuration->Change Podcast Generator Configuration"
and then "Enable Social Networks Integration?".
And you just dissable it.
