### ISSUE TITLE
Unable to submit podcast to iTunes

### ISSUE THREAD

**Issue by MrCarter2959** [albertobeta/PodcastGenerator#105]
Anyone run into not being able to submit the podcast into iTunes by using the RSS url? iTunes sends a email confirmation that says " An error was encountered while trying to add your feed. Please correct the error and submit your feed again. For additional information, please consult the podcast FAQ " 

It doesn't actually tell me what's wrong with the podcast. I used the two URL's that Apple includes and the Podcast checker they link, comes back with 100% pass rate and all green checks. Any ideas?

**Comment by djlucawolf** [comment]
Try to create the new podcast with the rss link directly on podcastsconnect.apple.com
