### ISSUE TITLE
Advisory - Podcastgen 2.7 - Stored XSS

### ISSUE THREAD

**Issue by DanielBishtawi** [albertobeta/PodcastGenerator#108]
Hello,

While testing the Netsparker web application security scanner we identified Reflected and Stored Cross-site scripting vulnerabilities in PodcastGenerator 2.7. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details.

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by albertobeta** [comment]
https://github.com/albertobeta/PodcastGenerator/commit/8d797763e244a29b9e46f1047e5f4640a506247f
