### ISSUE TITLE
Tracking & Analytics

### ISSUE THREAD

**Issue by nataliesw** [albertobeta/PodcastGenerator#112]
What are some ways we can get analytics for tracking how many podcast downloads we are getting?  We have tried podtrac, but it only tracks from the clicks made from the podtrac links.

**Comment by radiostorm** [comment]
Modifying the functions.php works as a hack for now:

https://github.com/albertobeta/PodcastGenerator/issues/86

Be careful and back up the file before you change it, took me almost an hour to figure out the right syntax to have it work (I used podbean analytics)

**Comment by nkomarov** [comment]
It would be cool to add settings with fields for Google Analytics of similar tracking HTML codes. Normaly it is in two pieces - one in HEAD and on before the </body>
