### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by kryten3000** [albertobeta/PodcastGenerator#114]
I have entered the Admin section and under 'Help' there is an option for: Your server configuration
Upon entering this section I am encountered with the following error across the top of the page:

Notice: A non well formed numeric value encountered in /.../core/admin/server_info.php on line 58

Line 58 reads as follows:
$showmin = min($max_upload_form_size_MB, ini_get('upload_max_filesize')+0, ini_get('post_max_size')+0); // min function

1. What is the telling me (I'm a noob)?
2. How do I fix it?

Thank you.

**Comment by pettedemon** [comment]
Hi,
I try to delete +0 operations... but I think is not the solution

**Comment by pettedemon** [comment]
Hi,
the problem is with php 7?
