### ISSUE TITLE
no theme

### ISSUE THREAD

**Issue by PPPundits** [albertobeta/PodcastGenerator#117]
Have uploaded files and gone through the setup procedure, and deleted the setup folder. When I try to go to podgen page I get the following error  "Failed to open theme file" in the top left corner of the page. I already run Podgen on another domain (works sweet) but hosted by the same company. Everything appears the same file wise and can't figure out what I am doing wrong.. Hope you can help, cheers, John

**Comment by hatster85** [comment]
Did you ever figure this out? I'm in the same boat.
