### ISSUE TITLE
How do I access Podcast Generator externally on Synology NAS?

### ISSUE THREAD

**Issue by markw619** [albertobeta/PodcastGenerator#118]
I have Podcast Generator installed on a Synology NAS and it is working fine when I am using the intranet address i.e. 192.168.etc... I am using a URL shortener to access my server across the internet and would like to do the same with my Podcast Generator instance. 

Is Podcast Generator mapped to a specific port so that all of the requests coming through that port will be picked up by the app?

**Comment by steveod83** [comment]
I'm also having some trouble with this and wondered if it was related to port mapping. 

I installed through the Synology package centre on my DS918+, no errors reported through the setup process and I was able to create a podcast and the the feed successfully - however I can't access the feed outside of my local network, which I guess is why I'm getting the 'Cant read your feed' error through iTunes Connect. 

Any help on this would be greatly appreciate @markw619 I'm not sure if you've managed to resolve this?
