### ISSUE TITLE
Can't install, stoping at first setup with unspecific error

### ISSUE THREAD

**Issue by herpez** [albertobeta/PodcastGenerator#119]
I have apache2 and php7.0

When i go to localhost/pogcastgenerator/setup it shows a page saying

```
**Podcast Generator 2.7 Setup**

Step 1/3

Howdy! You are just 3 steps away to setup your podcast..
```

And that's it... I can't do the configuration.

**Comment by davidfdriscoll** [comment]
I think this is the same problem as: https://github.com/albertobeta/PodcastGenerator/issues/21

Installing php-gettext solved it for me.
