### ISSUE TITLE
Feature request: Support for iOS 11 iTunes podcast tags

### ISSUE THREAD

**Issue by alwa** [albertobeta/PodcastGenerator#122]
Would be great to support the new tags especially now that Apple threatens to block podcasts that are adding episode numbers in episode names.

Note: May overlap https://github.com/albertobeta/PodcastGenerator/issues/31

Reference (tags info):
https://theaudacitytopodcast.com/how-to-start-using-the-new-itunes-podcast-tags-for-ios-11-tap316/

**Comment by alwa** [comment]
@emilengler Is this in your plans for 3.0 you think?

**Comment by emilengler** [comment]
@alwa Thanks for the ping!
I used #146 and hope that they are the correct ones
