### ISSUE TITLE
Despite having the post limit and upload limit set high, and the config file above 100MB, can't upload large files

### ISSUE THREAD

**Issue by ilikenwf** [albertobeta/PodcastGenerator#13]
22mb audio files work fine, but if I try to upload a 243mb mp4, I get an error message claiming it's my upload max file size or permissions error.

I've looked through the php and see no reasons this should be happening and was wondering if you have a clue.

Host is Ubuntu 14.04 LTS, standard LAMP stack with upload and post max set to 16GB (owncloud)

**Comment by albertobeta** [comment]
I would try to check line 56 here:
https://github.com/albertobeta/PodcastGenerator/blob/master/core/admin/upload.php#L56
Maybe this is preventing the upload of the file. Moreover make sure that the media folder has writing permission from the web (as a test try to chmod it to 777 and it should work, then you can try lower privileges than 777, such as 755 if possible)
