### ISSUE TITLE
Secure Server settings

### ISSUE THREAD

**Issue by AlexEneas** [albertobeta/PodcastGenerator#130]
Hello,
I have a secure server where I host my podcast (https), however when generating a podcast feed, how can i get the Generator to use https in the feed for the various links rather than just http?

Thanks

**Comment by gerega** [comment]
Project ist dead. No answers anymore.

**Comment by arshem** [comment]
The quickest way to do this is by replacing the $feed_URL_replace variable in config.php with the HTTPS version of your current feed URL.
