### ISSUE TITLE
iTunes Feed URL

### ISSUE THREAD

**Issue by amason101070** [albertobeta/PodcastGenerator#134]
Hi, I have setup my Synoloy NAS to run PG and it is working fine at the moment, but the issue I am having is when i link an episode with iTunes, although it syncs just fine with iTunes, the Itunes Podcast URL ends with feed.xml.

Where or what do i need to edit so the podcast URL points to the media folder instead of the RSS feed xml url? Basically while in itunes I click on "copy podcast url" the following is what it points to which is just raw rss feed xml. 

http://my-site-here/podcastgen/feed.xml

Note: (my-site-here) is only a filler site for privacy purposes.

I'm sorry, I am very new to PG and I am not even sure if this is how I should ask for help. If I am violating any posting rules, Please forgive me as it is not intentional.

Thank you,

Ron

**Comment by arshem** [comment]
iTunes needs an RSS file. That's what the feed.xml file is. If you point it to the media folder, itunes won't do anything.
