### ISSUE TITLE
PodcastGenerator no longer functioning after updating Wordpress Website

### ISSUE THREAD

**Issue by TechFreak19** [albertobeta/PodcastGenerator#136]
Hello, i recently updated my WordPress website to WP 5.2.2, and now our original weblink from our website to the podcast hosting/login goes straight to a 'HTTP ERROR 500' please can you to me what i can do to fix this, please note our current PG version is 2.2 will updating to 2.7 fix this error maybe? Thank you. Simon

**Comment by arshem** [comment]
Upgrading WordPress shouldn't affect your podcast generator, they are separate scripts. 500 errors generally refer to an internal issue.  Probably permissions
