### ISSUE TITLE
Podcasts aren't being found by PG 2.6

### ISSUE THREAD

**Issue by cyberialman** [albertobeta/PodcastGenerator#14]
Hi,
I'm new to PG (v2.6, exposure theme). I'm trying to upload my first mp3 episode. i can see the mp3 file in the media folder, but the ftp feature can't find it.  How do I load it please?

Thanks
Andrew

**Comment by albertobeta** [comment]
make a test: if you upload a small mp3 file through the PG admin interface, does it get stored into the media folder? 
Moreover make sure you have [writing permissions](https://github.com/albertobeta/PodcastGenerator/issues/15)?
