### ISSUE TITLE
Podcast Generator 3.0 - Progress

### ISSUE THREAD

**Issue by emilengler** [albertobeta/PodcastGenerator#147]
Hello, I talked with @albertobeta one or two months ago about taking over the project.
Now I found the time and motivation to finally start on it. I spend the last 4 days working on the rewrite but I did the same approach as the old codebase so I will be starting over because my current code and system is not that perfect.

The rewrite should have the following features:

- Backwards compatibility in terms of config, episodes and categories. No Database will be used
- A way to do esay updates
- Not a huge index.php with lots of HTTP GETS. Splitted in multiple files
- Using MVC (Probably a framework like Laravel, haven't digged myself that much into it yet)
- Because of this a new theme system as well
- A general modernization of the system
- Security (The old installs used MD5, I will add a converter agent to convert the old password to a newer)

I've written the Goals and Problems of the rewrite on a flipchart:
![](https://i.imgur.com/QlkrqXL.jpg)
I hope you can read my font

I will start working on it now in a more transparent way.
~You can follow the development in my forked repository in the `rewrite-3.0` branch.
https://github.com/emilengler/PodcastGenerator/tree/rewrite-3.0~
** The development happens now here in the `3.0` branch **

I will post progress here as a kind of diary.
Once I am done I will open a pull request on this repo

**Comment by emilengler** [comment]
I added a setup system

**Comment by emilengler** [comment]
Stuff that happened on the 27th of October 2019

Number of total commits: `8`

* Setup was added (recycled from my previous attempts)
* Added a **backwards-compatible** config system (recycled from my previous attempts)
* Added the base for the theme system
* Added category theme

Stuff I will plan to do tomorrow:
* Admin system with working authentication
* Uploading and processing a new episode

**Comment by emilengler** [comment]
Stuff that happened on the 27th of October 2019

Number of total commits: `2`

* Admin Interface was added (not done yet, just the beginning)
* Utf-8 encoding on all sites (nothing special)

Stuff I will plan to do tomorrow:
* Uploading and processing a new episode

**Comment by emilengler** [comment]
Stuff that happened on the 28th of October 2019

Number of total commits: `6`

* Bootstrap was made available globally (so less resources are used)
* Added a serious navbar with all links
* Added the mockup for the upload episode dialog

Stuff I will plan to do tomorrow:
* Uploading and processing a new episode (hopefully)

The day after tomorrow is a holiday in my state so you can expect from me that I will do more stuff tomorrow.

**Comment by emilengler** [comment]
Stuff that happened on the 30th and (the night of) 31th of October 2019

Number of total commits: `3`

* Uploading episodes works
* Parsing audio files

Stuff I will plan to do tomorrow:
* Feed generation
* More modulation, the current code is very clumpy and could be splited into more functions

**Comment by emilengler** [comment]
Stuff that happened on the 31th of October 2019
I had not much time and motivation today so the changes were very minimal

Number of total commits: `2`

* Base for the actual feed generation (header)
* Add subtitle to config

Stuff I will plan to do tomorrow:
* Finalize feed generation

**Comment by emilengler** [comment]
Stuff that happened on the 1st of November 2019
I had not much time today and I'm busy tomorrow as well

Number of total commits: `2`

* Set file upload date if in future
* Get audio meta data (the original code got lost apparently)

Stuff I will plan to do tomorrow:
* Finalize feed generation (hopefully lol :P)

**Comment by emilengler** [comment]
Stuff that happened on the 2nd of November 2019
I had not much time today and I'm busy tomorrow as well (again)

Number of total commits: `1`

* Get episodes in correct order (feed generator)
* Drop episodes from the future

Stuff I will plan to do tomorrow:
* Finalize feed generation (hopefully lol :P)

**Comment by emilengler** [comment]
I had no time today (3rd of November 2019)
Will do it tomorrow

**Comment by emilengler** [comment]
Stuff that happened on the 2nd of November 2019
I had not much time today and I'm busy tomorrow as well (again)

Number of total commits: `4`

* Finished feed generation YAY! Will test it tomorrow

Stuff I will plan to do tomorrow:
* FTP Auto Indexing

**Comment by emilengler** [comment]
Stuff that happened on the 5th of November 2019
I had not much time today and I'm busy tomorrow as well (again)

Number of total commits: `1`

* Manual RSS feed generation

Stuff I will plan to do next:
* FTP Auto Indexing

**Comment by emilengler** [comment]
Stuff that happened on the 6th of November 2019
I had not much time today and I'm busy tomorrow as well (again)

Number of total commits: `1`

* FTP Auto Indexing

Stuff I will plan to do next:
* Fix bug in the feed generation (episodes in the futures does not really work)
* Category manager

**Comment by Go-rom** [comment]
Thank you for keeping us updated about your work on PG.
I'm not a dev but i can help with french translation.

**Comment by emilengler** [comment]
@Go-rom Thanks, I will do the translation stuff shortly before the release. I will contact you then

**Comment by arshem** [comment]
This is great! I was just reworking it into CodeIgniter. Awesome. Following your progress :)

**Comment by emilengler** [comment]
First, thanks for your feedback @Go-rom and @arshem :)
Now, lets start with daily news
---
Stuff that happened on the 7th of November 2019
Tomorrow is weekend and I'll be at home at around 11:30AM so I have lots of time :)

Number of total commits: `7`

* Feed Generation bug fix (works now with older episodes and future episodes)
* Fix bug in FTP Feature (It indexes all episodes now)
* Add category manager

Stuff I will plan to do next:
* Episode overview on the website
* The fake cron no that the feed is generated at that time when an episode should be released

**Comment by emilengler** [comment]
Stuff that happened on the 8th of November 2019 and a bit 9th of November 2019

Number of total commits: `7`

* Edit/Delete Episodes
* Episodes are shown on the main page

Stuff I will plan to do next:
* The fake cron no that the feed is generated at that time when an episode should be released
* Freebox
* Theme Chooser

**Comment by emilengler** [comment]
Stuff that happened on the 9th of November 2019 and a bit 10th of November 2019

Number of total commits: `8`

* Freebox
* Freebox Editor
* Bug fix in index
* Theme switcher
* Theme preview and json metadata
* Cover switcher

Stuff I will plan to do next:
* The fake cron no that the feed is generated at that time when an episode should be released
* Freebox
* Podcast Category Selector
* Podcast Detail Chooser
* Podcast Generator Config Chooser

**Comment by emilengler** [comment]
Stuff that happened on the 9th of November 2019 and a bit 10th of November 2019

Number of total commits: `8`

* Category manager

Stuff I will plan to do next:
* The fake cron no that the feed is generated at that time when an episode should be released
* Podcast Detail Chooser
* Podcast Generator Config Chooser
* Buttons editor
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 9th of November 2019 and a bit 10th of November 2019

Number of total commits: `4`

* Podcast Detail Editor
* Podcast Generator Config Editor

Stuff I will plan to do next:
* The fake cron no that the feed is generated at that time when an episode should be released
* Buttons editor
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 11th of November 2019

Number of total commits: `2`

* Cron
* Buttons system

Stuff I will plan to do next:
* Warning fixes
* Security fixes
* Translation system (especially themes will become problematically)

**Comment by AmritasyaPutra** [comment]
Good work, best wishes.

**Comment by emilengler** [comment]
Stuff that happened on the 13th of November 2019

Number of total commits: `1`

* Category system fix

Stuff I will plan to do next:
* Warning fixes
* Security fixes
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 14th of November 2019

Number of total commits: `2`

* Security Fixes (XSS) If someone is good at PHP security, feel free to test it :)
* Warning Fixes

Stuff I will plan to do next:
* Warning fixes (Some are still missing, especially in admin area)
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 15th of November 2019

Number of total commits: `0`

Nothing, sorry :(

Stuff I will plan to do next:
* Warning fixes (Some are still missing, especially in admin area)
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 16th of November 2019

Number of total commits: `1`

* Backwards comp.

Stuff I will plan to do next:
* Warning fixes (Some are still missing, especially in admin area)
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 17th of November 2019

Number of total commits: `4`

* Some Config specific backwards comp.

Stuff I will plan to do next:
* Config specific backwards comp.
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 18th of November 2019

Number of total commits: `6`

* Some Config specific backwards comp.
* Buf fixes

Stuff I will plan to do next:
* Config specific backwards comp.
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 19th of November 2019

Number of total commits: `0`

Nothing, no time sorry

Stuff I will plan to do next:
* Config specific backwards comp.
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
Stuff that happened on the 20th of November 2019

Number of total commits: `0`

Nothing, no time sorry

Stuff I will plan to do next:
* Config specific backwards comp.
* Backwards compatibility tests
* Translation system (especially themes will become problematically)

**Comment by emilengler** [comment]
**Podcast Generator 3 will be in English only!**
This has the reason that there are not sufficent people who are going to maintain the language files.
A new translation system will be added in PG 3.1
More infos will follow soon

**Comment by alwa** [comment]
@emilengler Please let us know which languages you need translators for. I can help out with Swedish for example.

**Comment by Go-rom** [comment]
Yes i agree, English will be fine for now.

**Comment by emilengler** [comment]
Yes, then I think I'm going to release PG this weekend.
The community needs to get "reactivated" so we get more maintainers.
In terms of features PG is done.
It only needs some testing.
However PG 3 won't have much new features it will only be a rewrite plus a buttons editor feature. The new features will follow in PG 3.1

**Comment by emilengler** [comment]
Stuff that happened on the 21th of November 2019 and a bit of 22th of November 2019

Number of total commits: `9`

* Podcast Generator News Display
* Mobile friendly
* Page view
* Category bug fixes ($link)
* Theme fallback
* episodeperpage
* iTunes as a default button

Stuff I will plan to do next:
* Config specific backwards comp.
* Backwards compatibility tests

**I aim to do the final release on Sunday but I can't guarantee anything so far.**
I will contact @albertobeta then.

**Comment by plothost** [comment]
Will this version work on PHP 7.3/7.4? Thank you.

**Comment by emilengler** [comment]
@plothost 
The question is more if it will work with versions older than 7.3 as I only tested it with it :)

**Comment by plothost** [comment]
@emilengler Great :) Thank you.

**Comment by emilengler** [comment]
Stuff that happened on the 23th of November 2019

Number of total commits: `0`

Nothing, sorry :(

**Comment by emilengler** [comment]
Stuff that happened on the 21th of November 2019 and a bit of 22th of November 2019

Number of total commits: `4`

* Implement feed_dir
* Implement Implement categoriesenabled
* Bug fixes

Stuff I will plan to do next:
* New config engine (the current one is too buggy, I got the idea for a smoother way. Needs to be done before release)
* Backwards compatibility tests
* New folder structure (The root dir should be a meta dir with the src folder in it)
* Bug fixes (If there are any)

**Unfortunately I wasn't able to finish PG on Saturday so I will probably do the release during this week.**

**Comment by madsha** [comment]
Great work, can't wait to try it out.

Will PG support the tag:
<itunes:duration>

Will podtrac integration be possible, as in the current PG, by editing line 1387 in 'functions.php'?

/Mads Hansen

**Comment by alancontino** [comment]
I've got a server setup for install and is ready for testing.   Do you have an install package or setup procedure that will come with the release?

**Comment by emilengler** [comment]
@madsha 
> Will PG support the tag:
itunes:duration

Yes

> Will podtrac integration be possible, as in the current PG, by editing line 1387 in 'functions.php'?
I don't know what that is but after looking at line 1387 it should be possible by adding this to `106` in `core/feed.php` in my rewrite

@alancontino 
On Debian 10 you just need the packages `php` and `php-xml`. That's it no DB. A web server is required for sure. I can write a shell script but I don't think it is neccesary. The only problem that could occur might be file permissions. It might help to do `chmod 777 /path/to/your/podcastgenerator` and `chmod 777 -R /path/to/your/podcastgenerator/media` `chmod 777 -R/path/to/your/podcastgenerator/images`

**Comment by emilengler** [comment]
Stuff that happened on the 25th of November 2019

Number of total commits: `3`

* Bug fixes
* Warning fixes
* New configuration system (still 100% backwards compatible with older files, just needs some more testing)

Stuff I will plan to do next:
* Backwards compatibility tests
* New folder structure (The root dir should be a meta dir with the src folder in it)
* Bug fixes (If there are any)

**Comment by madsha** [comment]
Hi Emil, in the old PG, the edit to line 1387 goes like this:

Original line is:
<enclosure url="'.$url.$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>

Edit to:
<enclosure url="'."http://dts.podtrac.com/redirect.mp3/kkb-lyd.dk/maanedens/".$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>

kkb-lyd.dk/maanedens is of course specific to me


What would I need to do in the new PG?


With regards,
Mads Hansen

Fra: Emil Engler <notifications@github.com>
Sendt: 25. november 2019 20:20
Til: albertobeta/PodcastGenerator <PodcastGenerator@noreply.github.com>
Cc: Mads Hansen <madsha@kk.dk>; Mention <mention@noreply.github.com>
Emne: Re: [albertobeta/PodcastGenerator] Podcast Generator 3.0 - Progress (#147)


@madsha<https://github.com/madsha>

Will PG support the tag:
itunes:duration

Yes

Will podtrac integration be possible, as in the current PG, by editing line 1387 in 'functions.php'?
I don't know what that is but after looking at line 1387 it should be possible by adding this to 106 in core/feed.php in my rewrite

@alancontino<https://github.com/alancontino>
On Debian 10 you just need the packages php and php-xml. That's it no DB. A web server is required for sure. I can write a shell script but I don't think it is neccesary. The only problem that could occur might be file permissions. It might help to do chmod 777 /path/to/your/podcastgenerator and chmod 777 -R /path/to/your/podcastgenerator/media chmod 777 -R/path/to/your/podcastgenerator/images

**Comment by emilengler** [comment]
@madsha At the moment, edit Line 106 in `core/feed.php`
You could try this:
```
<enclosure url="http://dts.podtrac.com/redirect.mp3/kkb-lyd.dk/maanedens/'.$config["upload_dir"].$files[$i]["filename"].'" length="' . filesize($config["absoluteurl"] . $config["upload_dir"] . $files[$i]["filename"]) . '" type="' . mime_content_type($config["absoluteurl"] $config["upload_dir"] . $files[$i]["filename"]) . '"></enclosure>
```
I haven't tested it and it might change before the release. If it does not work, just open an issue here

**Comment by emilengler** [comment]
Stuff that happened on the 26th of November 2019

Number of total commits: `2`

* New folder hierarchy
* A bug fix in the config system

Stuff I will plan to do next:
* Fix bug in getConfig
* Backwards compatibility tests
* New folder structure (The root dir should be a meta dir with the src folder in it)
* Bug fixes (If there are any)

**Comment by madsha** [comment]
Hi Emil,

Thanks.

Is there any chance that the new PG will run on PHP 5.2.17?

The old PG runs…

Regards,
Mads Hansen

Fra: Emil Engler <notifications@github.com>
Sendt: 26. november 2019 17:43
Til: albertobeta/PodcastGenerator <PodcastGenerator@noreply.github.com>
Cc: Mads Hansen <madsha@kk.dk>; Mention <mention@noreply.github.com>
Emne: Re: [albertobeta/PodcastGenerator] Podcast Generator 3.0 - Progress (#147)


@madsha<https://github.com/madsha> At the moment, edit Line 106 in core/feed.php
You could try this:

<enclosure url="http://dts.podtrac.com/redirect.mp3/kkb-lyd.dk/maanedens/'.$config["upload_dir"].$files[$i]["filename"].'" length="' . filesize($config["absoluteurl"] . $config["upload_dir"] . $files[$i]["filename"]) . '" type="' . mime_content_type($config["absoluteurl"] $config["upload_dir"] . $files[$i]["filename"]) . '"></enclosure>

I haven't tested it and it might change before the release. If it does not work, just open an issue here

**Comment by emilengler** [comment]
@madsha 
I will test before release

**Comment by emilengler** [comment]
Stuff that happened on the 27th of November 2019

Number of total commits: `0`

* Nothing special sorry

Stuff I will plan to do next:
* Fix the password converter
* Revert to old config system or a different approach
* Backwards compatibility tests
* Bug fixes (If there are any)

**Comment by emilengler** [comment]
Sorry for being inactive the last days, I will probably continue so until the 19th of December as I write lots of exams during that time span

Stuff that happened on the 28th-30th of November 2019

Number of total commits: `0`

* Nothing special sorry

Stuff I will plan to do next:
* Fix the password converter
* Revert to old config system or a different approach
* Backwards compatibility tests
* Bug fixes (If there are any)

**Comment by emilengler** [comment]
Stuff that happened on the 1st of December 2019

Number of total commits: `3`

* Config system fixes
* Password Converter improvement
* Better backwards comparability

Stuff I will plan to do next:
* Only open the password converter if the version is 2.7
* Backwards compatibility tests
* Bug fixes (If there are any)

**Comment by emilengler** [comment]
Thanks to Alberto, I got write access to the repository. I will continue working here!

**Comment by emilengler** [comment]
The development branch has moved from my local fork to the 3.0 branch in this repo

**Comment by emilengler** [comment]
Stuff that happened on the 2nd of December 2019

Number of total commits: `1`

* Bug fix in include
* Repository moved here, got write accesss

Stuff I will plan to do next:
* Only open the password converter if the version is 2.7
* Backwards compatibility tests
* Bug fixes (If there are any)
* TRANSLATION SYSTEM!!!!

**Comment by emilengler** [comment]
**PG 3 will have translations (at least a system for it), more infos will come soon**

**Comment by Go-rom** [comment]
Great, thank you !

**Comment by emilengler** [comment]
Sorry that not much happened the last days, I have written lots of exams and got an eye infection (nothing serious) however I can't really be that productive though so please excuse my possible inactivity

**Comment by Go-rom** [comment]
Well, year-end is not an easy time for everyone so don't apologize.
We know that PG3 will get a release soon or later, it will be a good news to start 2020.

Best wishes

**Comment by emilengler** [comment]
I just deleted all tags and release information. This was done because the tags were named the same as the new branch name schema.
However the release information is not gone.
I placed them with download links into a file for archiving purposes :)
See https://github.com/albertobeta/PodcastGenerator/blob/3.0/LEGACY.md

**Comment by emilengler** [comment]
ping @Go-rom 
Translations are now open!
Please help if you can speak a language that is not english :)
https://www.transifex.com/albertobeta/podcast-generator/30/

**Comment by emilengler** [comment]
Translation will close on 31th of December 2019.
Will release then if the documentation is done :)

**Comment by alwa** [comment]
Question: When upgrading from 2.7 to 3.0, what data will be lost (or maybe rather what will be preserved)?
When upgrading 2.x I believe that category metadata is lost, at least, for old episodes.

**Comment by emilengler** [comment]
@alwa When developing PG 3.0 I kept backwards compatibility in mind.
No data will be lost (except changes you made in the code or theme) :)

**Comment by emilengler** [comment]
Maybe some (very unimportant) configuration settings may not work anymore. However this doesn't really affect your experience

**Comment by emilengler** [comment]
Dear translators, due tomy fault I forgot to include some sentences into the translation system.
Could you also tranlate them? They are just 10 :)

**Comment by emilengler** [comment]
Otherwise I would need Google Translate which is highly unprofessional. The stuff that needs to be translated is also really important though :(
(It's the menu bar in the admin area)

**Comment by emilengler** [comment]
Just closed all 2.7 related issues and PR

**Comment by Go-rom** [comment]
Great, a fresh start !

I'm new with Transifex, French localization for PG 3.0 is done but i can't reach the 100% progress bar. Lots of strings remain not translated in the legacy section, Transifex says "it's closed"

**Comment by emilengler** [comment]
@Go-rom Thanks for the translation. Yes, Legacy is closed because it is for 2.7

**Comment by emilengler** [comment]
We are done!
Thanks for everyone who helped :)
PG 3 is available now: https://github.com/albertobeta/PodcastGenerator/releases/tag/v3.0

**Comment by emilengler** [comment]
Also happy new year to all of you :)

**Comment by plothost** [comment]
Thanks for your work.

Happy New Year!

**Comment by RealLongwayround** [comment]
Now that v3.0 is out, how can I download v2.7? My current installation uses v2.5 and I believe I need v2.7 in order to upgrade to v3.

Thanks.

--
Luke Bosman
— Sent from Polymail ( https://polymail.io/ )

**Comment by emilengler** [comment]
@RealLongwayround Yes you need 2.7.
It is available here: https://github.com/albertobeta/PodcastGenerator/releases/tag/v2.7

**Comment by alwa** [comment]
@emilengler Would you consider updating http://www.podcastgenerator.net/download to point to 3.0?

**Comment by emilengler** [comment]
@alwa Yes. However I don't have access to the website yet. I made a new website available at (https://podcastgenerator.github.io). I'm just waiting for Alberto as he controls the domain

**Comment by AmritasyaPutra** [comment]
Wonderful! May I request a very simple cosmetic change to the new website? On https://podcastgenerator.github.io/download.html the all caps in solid red background appears little intimidating, maybe we can make it more inviting.

On Help page: "Our documentation is currently edited. Sorry. However you can ask for help wit GitHub Issue." is little cryptic, it can be made a little more simple and direct, something like "We are working on our documentation, sorry for the inconvenience, meanwhile you can ask for help on GitHub(linked word)."

Thank you.

**Comment by emilengler** [comment]
Sure. However you are free to open a pull request in https://github.com/PodcastGenerator/PodcastGenerator.github.io

**Comment by Go-rom** [comment]
Hello @emilengler 

many thanks for this great 3.1 release.
About the french translation, i will handle it soon.

**Comment by emilengler** [comment]
thanks

**Comment by Go-rom** [comment]
Hello @emilengler 

I'm ready to test the french translation with PG 3.1
Transifex provides me the .po file. How do i get the .mo file ?

Thank you and happy new year ! Which is also a kind of anniversary since you've released PG 3.0 on 31 dec 2019 so 🎉 🎂

**Comment by Go-rom** [comment]
Hello @coldacid 

do you have the answer about my previous question please ?

Thank you ;)

**Comment by coldacid** [comment]
@Go-rom I couldn't say because I haven't touched anything regarding translations and I've never used Transifex.

**Comment by Go-rom** [comment]
Ok, thank you for your answer 😉

**Comment by emilengler** [comment]
@Go-rom I think I have answered you the question on Mastodon already. However don't worry about testing the translations. Of course it never hurts to test but by no means it is mandatory :-)

**Comment by Go-rom** [comment]
@emilengler Yes you have ;)
