### ISSUE TITLE
Install in cPanel via Softaculous doesn't let Setup function

### ISSUE THREAD

**Issue by alancontino** [albertobeta/PodcastGenerator#148]
Does the installation still work in the most recent CPanel/WHM environment under CentOS7 ??

I've run the install and the PHP functions do not run at all - setup doesn't even load.  

I'm getting this error message:

Fatal error: Uncaught Error: Call to undefined function mb_detect_encoding() in /home/newradio/public_html/podcast/components/php-gettext/gettext.inc:177 Stack trace: #0 /home/newradio/public_html/podcast/components/php-gettext/gettext.inc(279): _encode('Podcast Generat...') #1 /home/newradio/public_html/podcast/components/php-gettext/gettext.inc(286): _gettext('Podcast Generat...') #2 /home/newradio/public_html/podcast/components/php-gettext/gettext.inc(497): __('Podcast Generat...') #3 /home/newradio/public_html/podcast/setup/index.php(23): _('Podcast Generat...') #4 {main} thrown in /home/newradio/public_html/podcast/components/php-gettext/gettext.inc on line 177

**Comment by plothost** [comment]
Yes, it's working on cPanel and CentOS 7 and PHP 7.0
We have a few installations on our servers.
Do you have the mbstring extension installed?
