### ISSUE TITLE
"amp" is stripped from filename when uploading an episode

### ISSUE THREAD

**Issue by alwa** [albertobeta/PodcastGenerator#149]
Version 2.7

The FTP auto indexing seems to incorrectly convert "amp" into "_" when I am guessing that it tries to strip "&\amp;" or similar. In my case the surrounding text were just alphabetical characters which is completely harmless.

Example:
Kampen.mp3 becomes k_en.mp3

**Comment by Go-rom** [comment]
Hello,
2.7 version is now deprecated and won't be updated anymore.
3.0 is coming soon.

See this : https://github.com/albertobeta/PodcastGenerator/blob/3.0/LEGACY.md

**Comment by emilengler** [comment]
Thanks @Go-rom for the clarification :)
As 3.0 is really nearly before the release (just some testing and a small addition in the installer before the translation will happen). After this we might get 3.0 in this year :)
