### ISSUE TITLE
Can't create categories

### ISSUE THREAD

**Issue by cyberialman** [albertobeta/PodcastGenerator#15]
Hi,
I'm using PG v2.6, exposure theme. When I add a new category I get the following message:
New category: Sermons
Category added!

But, when I return to category management, the category has not been added to the list.  I've tried several times including logging out and in again.  I've also tried the syndicate theme and got the same problem.

What do I do please?

Thanks
Andrew

**Comment by albertobeta** [comment]
Make sure the file categories.xml is writable (chmod 755 or 777).
See the [list of files and folders that must have writing permissions](http://www.podcastgenerator.net/documentation/upgrade).
