### ISSUE TITLE
Open Graph Tag - og:image = URL?

### ISSUE THREAD

**Issue by cyros74** [albertobeta/PodcastGenerator#150]
Hi, can you help with the URL for the Open Graph tag (og:image)? What goes in place of the xxx?

`<meta property="og:image" content="xxx" />`

This didn't work: `<meta property="og:image" content="'.$text_imgpg.'" />`
Located at:  /core/teplates.php

Thanks

**Comment by cyros74** [comment]
Hi, can you help with the URL for the Open Graph tag (og:image)? What goes in place of the xxx?

`<meta property="og:image" content="xxx" />`

This is located at: /core/teplates.php

Thanks

**Comment by cyros74** [comment]
I found the solution:
`
$episodeURLreconstructed = $url.'?name='.avoidXSS($_GET['name']);
$imagename = $url.$img_dir.avoidXSS($_GET['name']);
$without_extension = basename($imagename, '.mp3');
			
// then ADD SOME OPEN GRAPH META TAGS
$metatagstoreplace .= '
	<meta property="og:image" content="'.$url.$img_dir.$without_extension.'.jpg">
`

**Comment by emilengler** [comment]
Thanks but keep in mind that PG 2.7 will soon be dead after 3.0 will be published probably this month.
