### ISSUE TITLE
Swap short description for long description 

### ISSUE THREAD

**Issue by visualisedata** [albertobeta/PodcastGenerator#154]
Is there a quick & easy way to remove the Short Description from the form and use the Long Description in it's place is the XML file ?

**Comment by visualisedata** [comment]
Any tips/advice on this ? I've tried a few things but I can't get it working properly.  Basically I don't want to be limited to 255 characters for the Short Description.  This seems to be a rule that no podcasts follow these days and I want to replace the Short Description with the Long Description in all cases.

**Comment by emilengler** [comment]
Hello @visualisedata.
Sorry but PG 2.7 is dead.
I'm working on version 3.0
I will include a feature to change the max size of the short description.
However keep in mind that these standards do exist for reasons

**Comment by visualisedata** [comment]
I know what you mean when you say "it's dead", BUT ... 

- according to github it's the latest release
- according to the website it's the version you download when you want to use it

I don't understand the github standards perfectly, but IMHO you're only catering for the current users.  I'm wanting to use 2.7 NOW because it's stable and I need some help with changing the code.  I don't want to wait for 3.0 to be stable (or even try to figure out how to install it).

So I'll keep track of this project, but I'll just settle for 2.7 the way it is now and make changes where I want when my knowledge gets up to the level where it will work properly.

**Comment by emilengler** [comment]
> according to github it's the latest release

This has nothing to say

If you really want to change it, you could edit the episode details in the associated XML file in the `media/` folder. There it won't check for anything including character limits

**Comment by emilengler** [comment]
I had no time to implement this feature in PG3. If you still want, you can modify the XML file of the episode in the `media/` directory, this should definitely work.
