### ISSUE TITLE
PG 2.X to 3.0 upgrade - Theme configuration is not reset

### ISSUE THREAD

**Issue by Go-rom** [albertobeta/PodcastGenerator#158]
Hello @emilengler 

a quick feedback about PG upgrade from 2.X to 3.0
In my case, i was using a custom theme for PG 2.X (exposure) and i think that the upgrading process to 3.0 doesn't reset the theme configuration in order to set the default theme.

**What's happening ?**

After password conversion, we get a blank page

**What's expected ?**

After password conversion, we have to get the home page

**Workaround**

Make a copy of the file "config.php" (backup) then open it with a basic text editor.
Look after this line : `$theme_path =`
At the same line, you have to type this : `$theme_path = "themes/default/";`
Save the file then upload it.
It's done

Thank you for this release btw

**Comment by emilengler** [comment]
Hmm interesting.
Maybe a reload of the site when you get a blank site helps?
The theme is going to be set to to `themes/default/` though.
Were other values of the config.php changed?
Like the version number?

**Comment by emilengler** [comment]
Note for developers: https://github.com/albertobeta/PodcastGenerator/blob/0e49b5c1a319bfd742031c8d97e4c303c7e269bc/PodcastGenerator/core/backwards.php#L96

**Comment by Go-rom** [comment]
The only modified value in the config.php is `$userpassword` (so nothing strange since the password conversion from md5 to bcrypt)
Version number is still at 2.6

I had to re-upload the covert art, mine was replaced by the default one.

And i don't if it's relevant or not but my PG root folder is named "podcast" and not "podcastgen" or "podcastgenerator".

**Comment by emilengler** [comment]
> And i don't know if it's relevant or not but my PG root folder is named "podcast" and not "podcastgen" or "podcastgenerator".

This isn't relevant

> Version number is still at 2.6

There is the problem, it needs to be 2.7 ;)

**Comment by emilengler** [comment]
Change it and access any page. Your config will get updated then immediately.

Also as a more personal note. Due to a lazy mistake on my site, your french translation gets deleted when upgrading from 2.7. I added a fix note to the release note. Sorry. It's my first bigger project which I maintain so it's probably normal that I do some mistakes...

**Comment by Go-rom** [comment]
Ok, changing `$podcastgen_version` value from 2.6 to 2.7 did the trick. I didn't know that i wasn't up to date on the 2.X branch so that means that the upgrade requires 2.7 at least, thank your for your help.

Fun fact about french translation, it worked with my 2.6 setup so i didn't see that it was missing !
Don't worry about that, now that i saw it in french i have to rewrite some translations.

**Comment by Go-rom** [comment]
I'm closing this issue. Maybe, an additional note about PG 2.7 as minimum requirement could be useful.
