### ISSUE TITLE
Add a login page with password

### ISSUE THREAD

**Issue by Invictaz** [albertobeta/PodcastGenerator#160]
Add a login page with password so only users who have the password can see the podcast page.

**Comment by emilengler** [comment]
It could be done only partial. Users could still see the `feed.xml` as long as you don't restrict it with some OS side tweaks.
It would only work on stuff like the start page etc.

**Comment by Invictaz** [comment]
That is good enough.

**Comment by emilengler** [comment]
Ok, will work on that

**Comment by emilengler** [comment]
Feature was added with 87eb7a7.
It has the security risk described above
