### ISSUE TITLE
Pagination doesn't work

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#168]
My podcast has 500+ episodes, but PG3.0 (which is configured to show 20 episodes per page) shows only a single page of episodes.  (See https://podcasts.pbcharrisburg.org/ for live example.)

**Comment by cmpilato** [comment]
Stop the presses!  I think this was my fault.  I had only 20 episodes configured in `max_recent`, and 20 episodes in `episodeperpage` ... thus, one page.

**Comment by emilengler** [comment]
As an extra information:
`max_recent` is more global. It also hides these episodes in the feed.
`episodeperpage` is only GUI relevant it doesn't affect the feed generation
