### ISSUE TITLE
Host MP3 files on Dropbox

### ISSUE THREAD

**Issue by tiborepcek** [albertobeta/PodcastGenerator#169]
Hi and thank you very much for this great tool.

I would like to know, if i can host my MP3 files on Dropbox or do i have to upload it do the media folder of PG?

I self host [PG 3.0](https://github.com/albertobeta/PodcastGenerator/releases/tag/v3.0).

**Comment by emilengler** [comment]
We plan to add such a feature with 3.1.
Currently this is not possible, sorry
