### ISSUE TITLE
"Episode does not exist" viewing old episodes

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#170]
While trying to view an older episode from my podcast, I'm given an "Episode does not exist" error.

You can see the category listing at http://podcasts.pbcharrisburg.org/categories.php?cat=1_john

Clicking into any particular episode gives the error.

**Comment by emilengler** [comment]
Does this error still exists?
Or is it fixed because of your `max_recent` change?

**Comment by cmpilato** [comment]
Tweaking `max_recent` has made my reported problem go away, but I believe there remains a problem with `max_recent` and its interpretation -- namely, that PG doesn't appear to consistently apply any particular interpretation of that value across its functionality.

If `max_recent = 20` means "pretend that only the most recent 20 episodes exist at all", then I should not have been able to see _any_ episodes with the `1_john` category, even when filtering by that specific category.  (FWIW, the presence of the word `recent` in this configuration value would seem to imply that this is, in fact, the _desired_ meaning of the value.)

If `max_recent = 20` means, however, "don't try to present any listing with more than 20 total (possibly paginated) episodes", then even with `max_recent = 1`, I should never see an error attempting to view a single episode.

I'll concede that perhaps there's some other meaning that `max_recent = 20` might have.  I just can't discern what it might be.

**Comment by emilengler** [comment]
> If max_recent = 20 means "pretend that only the most recent 20 episodes exist at all", then I should not have been able to see any episodes with the 1_john category, even when filtering by that specific category. (FWIW, the presence of the word recent in this configuration value would seem to imply that this is, in fact, the desired meaning of the value.)

This is actually a part of the design. `max_recent` only affects the feed and the homepage.

I think this can be closed now, let me know if it should remain open

**Comment by cmpilato** [comment]
If `max_recent` is only intended to affect the feed and homepage, then I would expect not to get an "Episode does not exist" error when trying to view a single episode.  Even with `max_recent = 20`, 20 > 1. :grinning:

**Comment by emilengler** [comment]
@cmpilato An advantage of `max_recent` is also a performance incremental. If we would still scan for the episode it would be useless resources.

**Comment by emilengler** [comment]
I removed the ability to change max_recent from the web interface in 3.0.1.
In just causes more problems than it probably solves. If users still want the feature, they need to change it form the config.php
