### ISSUE TITLE
Old PG2.7 archive (and perhaps other) URLs broken by PG3.0 upgrade

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#172]
PG3.0 brought changes to the URL syntax for podcast listings and related views, which means that old bookmarks to those things are broken. I know it can be frustrating to maintain old URL syntaxes indefinitely (as my maintenance of ViewVC has taught me...), but where it's trivial to do so, it can greatly ease the end-user pain of upgrading to new versions.

**Comment by emilengler** [comment]
It changed it a bit.
The category and episode listings should still work fine.
Do you mean the admin and PG related urls? They have changed indeed.

**Comment by emilengler** [comment]
0118678 should have fixed this, thanks for the PR!
