### ISSUE TITLE
Feed generator should ignore non-media file types

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#174]
I've long had a utility script stored in my `media/` directory that helps me process podcast audio (named `post-audio`).  Today I noticed that either the FTP auto-index or the manual feed generation feature of PG3.0 (sorry, not sure which...) tried to process that file as episode data, renaming it to `2020-01-03-post-audio` and generating an `2020-01-03-post-audio.xml` metadata file for it.

PG should simply ignore files found in the media/ directory that are clearly not media files of supported types.

**Comment by emilengler** [comment]
Good idea, will work on this now.
I will inform you when it's done.
As you are a developer I think you know how to apply the patch then. (I should backport it to 3.0 for a 3.0.1 release)

**Comment by emilengler** [comment]
Fixed with 7d9f2a3e08175c09e77636723eb5a935a1e5b869
