### ISSUE TITLE
PG3.0: re-add ID3 support

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#177]
When adding (via the FTP feature) my first new podcast after upgrading to PG3.0, I noticed that it seems this new version has lost the ID3 tag scraping feature found in its predecessor, which means that MP3 titles, etc. are ignored and require subsequent editing through the PG admin interface.  It would be great to have that functionality restored.

**Comment by emilengler** [comment]
Currently we just get the bitrate and duration.
Didn't knew PG 2.7 supported also other MP3 tags.
will add this

**Comment by emilengler** [comment]
I added it with e1c4a659817971704bfeb031eac0418f40b5e6fe

Thanks for the suggestion :)

**Comment by emilengler** [comment]
Included in 3.0.1
