### ISSUE TITLE
PG3.0: "Save" button missing from episode edit form

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#178]
When attempting to edit the metadata of an episode, I find a "Delete" button and an "Edit" button, but no "Save" button.  Clicking "Edit" appears to reload the form, having discarded any modifications I've made.  As such, I can't find a way to modify episode metadata through the admin UI.

**Comment by emilengler** [comment]
The "Edit" button saves the episode. It works fine for me though.
As you have some problems with Podcast Generator, maybe you should give me your `config.php` so I can have a look at it. Please censor your user credentials before

**Comment by cmpilato** [comment]
Here ya go...

> $podcastgen_version = "3.0";
> $first_installation = 1577973660;
> $installationKey = "REDACTED";
> $scriptlang = "en_US";
> $url = "https://podcasts.pbcharrisburg.org/";
> $absoluteurl = "/home/pbcoffice/podcasts.pbcharrisburg.org/";
> $theme_path = "themes/pbcharrisburg/";
> $username = "REDACTED";
> $userpassword = "REDACTED";
> $max_upload_form_size = "104857600";
> $upload_dir = "media/";
> $img_dir = "images/";
> $feed_dir = "";
> $max_recent = "All";
> $recent_episode_in_feed = "All";
> $episodeperpage = 20;
> $enablestreaming = "yes";
> $freebox = "yes";
> $enablepgnewsinadmin = "yes";
> $strictfilenamepolicy = "no";
> $categoriesenabled = "yes";
> $cronAutoIndex = 1;
> $cronAutoRegenerateRSS = 1;
> $podcast_title = "Providence Baptist Church - Harrisburg, NC";
> $podcast_subtitle = "Providence Baptist Church";
> $podcast_description = "Providence Baptist Church is a church in Harrisburg, NC where God is moving and drawing people of all ages to become a part of His family. We are thrilled to be a part of this movement and invite you to experience it along with us.";
> $author_name = "Providence Baptist Church"; 
> $author_email = "podcasts@pbcharrisburg.org"; 
> $itunes_category[0] = "Religion & Spirituality:Christianity";
> $itunes_category[1] = "";
> $itunes_category[2] = "";
> $link = "?name=";
> $feed_language = "en";
> $copyright = "Copyright Providence Baptist Church.";
> $feed_encoding = "utf-8";
> $explicit_podcast = "no";

It may be worth noting that, as with PG2.7, in my installation the `media/` subdirectory is a symlink to another directory (for separation of code and content).

**Comment by cmpilato** [comment]
> The "Edit" button saves the episode. It works fine for me though.

Yeah, definitely not for me.  Clicking "Edit Episode" just refreshes the page without saving any of my changes.

**Comment by emilengler** [comment]
> It may be worth noting that, as with PG2.7, in my installation the media/ subdirectory is a symlink to another directory (for separation of code and content).

Maybe that's the problem. Some web servers have problems dealing with symliks. I will try to clone your setup the next days

**Comment by cmpilato** [comment]
The problem turned out to be that I hadn't selected a category for my episode.  I don't actually want a category for that episode (and PG2.7 didn't require them), so I've created PR #179 to allow categories to be optional (and to fix the bug that caused the "Missing fields" error not to be shown in the first place).

**Comment by emilengler** [comment]
Ok, will close this issue now as #179 will get merged.

**Comment by cmpilato** [comment]
Curious: why wasn't this backwards compat bugfix included in v3.0.1?

**Comment by emilengler** [comment]
> Curious: why wasn't this backwards compat bugfix included in v3.0.1?

It needs more testing with the case if categories are disabled. Sorry, didn't managed to do it until yet. But I see this as a non blocking issue
