### ISSUE TITLE
Convert Podhawk 1.85 to PodcastGenerator driven site

### ISSUE THREAD

**Issue by 5thtradition** [albertobeta/PodcastGenerator#18]
Can this be done somewhat painlessly ??? I have a huge Podhawk driven Podcast site and Podhawk is no longer in existence.  Any ideas would be appreciated

5thtradition.org

**Comment by albertobeta** [comment]
Not directly. But you can create a script with your favourite language (e.g. Ruby, Python etc.) to convert the Podhawk data into PG XML files (see info about their structure here: http://www.podcastgenerator.net/documentation/tech-xml-db).
