### ISSUE TITLE
Episodes without authors result in wonky feed.xml <author> elements

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#183]
While PG3.0 appears to require author metadata on episodes, its predecessor did not.  So my older episodes are resulting in `<author>` tags in `feed.xml` which look like so:

```
<author> ()</author>
```

The code should check to see if author names and/or email addresses are present in the metadata, build a string to encapsulate either or both as necessary, and use that string in the `<author></author>` elements.

**Comment by emilengler** [comment]
Fixed in 65eb9dc, thanks for the report

**Comment by emilengler** [comment]
Included in 3.0.1
