### ISSUE TITLE
Can´t login after installation

### ISSUE THREAD

**Issue by tellustheguru** [albertobeta/PodcastGenerator#184]
After I installed GP om my webserver and tried to login to admin, I got a error message:
Invalid username or password.

<img width="372" alt="bild" src="https://user-images.githubusercontent.com/47452862/72022119-fd42e600-326f-11ea-8b62-cd910b2af467.png">

**Comment by emilengler** [comment]
Do you have the error log for me?

**Comment by tellustheguru** [comment]
[Thu Jan 09 01:12:21.694794 2020] [php7:notice] [pid 16721] [client xxx.xxx.xxx.xxx:49050] PHP Notice:  Undefined offset: 0 in /xxx/xxx/PodcastGenerator/index.php on line 42
[Thu Jan 09 14:01:08.306007 2020] [php7:notice] [pid 8478] [client xxx.xxx.xxx.xxx:47048] PHP Notice:  Undefined offset: 0 in /xxx/xxx/PodcastGenerator/index.php on line 42

**Comment by emilengler** [comment]
Interesting, have you encountered any problems during the password converter step?

**Comment by tellustheguru** [comment]
This is a new install.

**Comment by tellustheguru** [comment]
I reinstalled, here is error log from installation:

[Thu Jan 09 16:20:03.793434 2020] [php7:notice] [pid 24631] [client xxx.xxx.xxx.xxx:38119] PHP Notice:  session_start(): A session had already been started - ignoring in /www-root/aljmedia/PodcastGenerator/setup/step3.php on line 13, referer: http://xxx.foo.xyz/PodcastGenerator/setup/step2.php
[Thu Jan 09 16:20:18.368145 2020] [php7:notice] [pid 24226] [client xxx.xxx.xxx.xxx:35033] PHP Notice:  session_start(): A session had already been started - ignoring in /www-root/aljmedia/PodcastGenerator/setup/step3.php on line 13, referer: http://xxx.foo.xyz/PodcastGenerator/setup/step3.php
[Thu Jan 09 16:20:18.403364 2020] [php7:notice] [pid 24226] [client xxx.xxx.xxx.xxx:35033] PHP Notice:  Undefined offset: 0 in /xxx/xxx/PodcastGenerator/index.php on line 42, referer: http://xxx.foo.xyz/PodcastGenerator/setup/step3.php

**Comment by NeoPangea** [comment]
Hi, I get this same error after a new install. The users.json file is missing after the install, and I did notice that during the install it asked me to provide the password twice. Where can I find the logs? I can only see the GET request successful in the HTML logs.

**Comment by emilengler** [comment]
OH!
You aren't using Podcast Generator 3.0!
You are using an unstable development build.
Please download 3.0 here: https://github.com/albertobeta/PodcastGenerator/releases/tag/v3.0

**Comment by tellustheguru** [comment]
Thanks, 
That solved the problem, now to get i to translate to swedish :)

**Comment by emilengler** [comment]
@tellustheguru Thanks!
Translating is possible here: https://www.transifex.com/albertobeta/podcast-generator/
