### ISSUE TITLE
Changing dates of podcasts 

### ISSUE THREAD

**Issue by scottgx** [albertobeta/PodcastGenerator#19]
Carried post over from https://sourceforge.net/p/podcastgen/support-requests/631/

I have a similar situation where I'm using a home server (Synology DS210, Linux and PHP 5.5.33). I chmod 777 the mp3 and xml files, but I am still not able to change the episode date using PG.  Am I missing something?

More info:  After selecting edit, I deleted the xml file (thinking this might help with setting the date), selected the date and time, and clicked "Update Episode."  The xml file was recreated but the podcast date was still taken from the date it was uploaded, not from the date I selected.

**Comment by albertobeta** [comment]
To change the date, PG uses the unix command touch. You have to make sure you have the permission to use "touch" via PHP. A quick and dirty test to see whether this is the problem would be locating the command touch in your filesystem and sudo chmod it temporarily to 777.
Check if after that you can change the dates through a PHP app such as PG.
