### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by EloFran** [albertobeta/PodcastGenerator#193]
HI,
It would be possible for someone to tell me how I can translate the chains of:
Filetype:
Size:
Duration:
Bibrate:

Thank you.

**Comment by emilengler** [comment]
Edit `themes/default/singleepisode.php` and `themes/default/listepisodes.php`. There search for the desired strings and replace them.

**Comment by EloFran** [comment]
Thx emilengler, I had changed themes/default/singleepisode.php, but no the other. 
greetings and thanks
