### ISSUE TITLE
Missing upgrade instruction (2.7 -> 3.0): "Save categories"

### ISSUE THREAD

**Issue by alwa** [albertobeta/PodcastGenerator#199]
I may be mistaken here (if so, please close this issue) but I don't think the upgrade instructions mentioned that you need to save podcast categories explicitly after upgrade.

You have to.
Otherwise you will get faulty (at least according to my web browser) feed XML with tags such as:

`<itunes:category text="Comedy"></itunes:category>
`
After save and regenerate RSS it becomes (which is fine by the browser):

`<itunes:category text="Comedy"/>`

**Comment by emilengler** [comment]
I probably misunderstand you but:
> <itunes:category text="Comedy"/>

is valid XML syntax. A tag can be closed both ways

**Comment by alwa** [comment]
@emilengler I don't know what to tell you more than that the browser complained before and now not on that very line.  Could it be that an XML element with an attribute cannot be empty in that way?

**Comment by emilengler** [comment]
Do you have a link to your feed so I can try it?

**Comment by alwa** [comment]
@emilengler well, now my feed has the "correct" format (after I saved) so I'm afraid not

**Comment by emilengler** [comment]
> @emilengler well, now my feed has the "correct" format (after I saved) so I'm afraid not

Are you sure that it won't broke again when you regenerate it

**Comment by alwa** [comment]
@emilengler I've regenerated many times and have not had any issues. As I stated earlier, the fix was to explicitly save categories once

**Comment by emilengler** [comment]
can this be closed?

**Comment by alwa** [comment]
@emilengler My problem is solved. It's more if this should be part of the upgrade instructions or not. I suppose that this is maybe just an XML rendering issue in a browser and nothing more serious. So I vote yes
