### ISSUE TITLE
new install; can't get to the page

### ISSUE THREAD

**Issue by MartiBurbeck** [albertobeta/PodcastGenerator#20]
I've installed PodcastGenerator according to the instructions and gone through the 3-step set-up process, but then get the message "The www.westpresa2.org page isn’t working" Any idea what's gone wrong? http://www.westpresa2.org/PodcastGenerator/

**Comment by albertobeta** [comment]
I checked out the page and there is no specific error. It looks like a server issue. I'd recommend to open a support ticket with your hosting provider and ask which is the specific error caused when visiting that page. Alternatively, if you have access to the servers logs you can check directly there.
