### ISSUE TITLE
Episode "More" links lead to nowhere?

### ISSUE THREAD

**Issue by alwa** [albertobeta/PodcastGenerator#200]
Preconditions:
- Upgraded from 2.7 (to 3.0)
- Some episodes pre-existing

Steps to reproduce:
- Go to Home
- For any podcast episode, click "More"

Expected:
To see all details about the episode (including description)

Actual:
Nothing happens. The link URL looks like:
http://mydomain/index.php?.

**Comment by emilengler** [comment]
This error happened to quite a few people.
Could you go to `config.php` line 92 and replace the line with this?
```
$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)
```
Tell me if the error still occurs

**Comment by alwa** [comment]
@emilengler it was not line 92 in my file but I found the entry and changed it and it seems to work!
However, I still cannot see the description of the episode, only the title and tagline, but I believe that is a separate issue.

**Comment by alwa** [comment]
@emilengler I'll close this issue now unless you feel you want to fix this in the upgrade script
