### ISSUE TITLE
Hardcoded texts (untranslateable)

### ISSUE THREAD

**Issue by alwa** [albertobeta/PodcastGenerator#202]
I've come across some texts that are not localized:

- "Logout - admin" (top right corner in admin menu)
- "Home" (second menu item in admin menu and also second menu item in unauthenticated menu)
- "Uncategorized" (In "Categories")
- "All Episodes" (In "Categories")

**Comment by emilengler** [comment]
The first two are intended to not be translated. I might be wrong on that but for example the german versions of these two strings sound a bit weird and are not common. I'm not sure about the others.

Uncategorized isn't really untranslated. It's just that the category has this name.

The last one is indeed a bug
