### ISSUE TITLE
Uploaded cover in "Podcast Platform Settings" not shown

### ISSUE THREAD

**Issue by alwa** [albertobeta/PodcastGenerator#203]
Steps to reproduce:
- Press "Change cover" under "Podcast Platform Settings"
- Upload a quadratic cover (JPG)
- Press Upload

Expected:
Current cover is shown

Actual:
A broken image icon. The URL to the image is mydomain/images/itunes_image.jpg

I looked inside the image folder and there is actually an image there, but it's called itunes_image.png

**Comment by alwa** [comment]
I edited "store_cover.php" and replaced occurrences of tunes_image.jpg with tunes_image.png and now it works

**Comment by emilengler** [comment]
This was already fixed a while ago :)
