### ISSUE TITLE
PG3.0 regression: auto-set missing long description to a copy of the short description

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#204]
PG2.7 would automatically store in the long description of an episode a copy of the short description (as part of the "save" action of editing an episode).  This is beneficial for folks (like myself) who have modified the singleepisode theme template to show the long description instead of the short, but who don't always have distinct long description content.

**Comment by emilengler** [comment]
Sorry but I don't understand

**Comment by cmpilato** [comment]
I fixed this with the pull request you just merged (#205).  I guess I goofed up the metadata and GitHub didn't associated that PR with this issue.

**Comment by emilengler** [comment]
Included in 3.0.1 which just got released.
Thanks for your PRs btw :)
