### ISSUE TITLE
Changes to button URLs (RSS and iTunes) not saved 

### ISSUE THREAD

**Issue by joerg-nafcom** [albertobeta/PodcastGenerator#208]
After updating podcast generator from 2.7 to 3.0 I had to re-set the Changes to button URLs (RSS and iTunes)
Albeit I can see it in the admin panel correct, on the homepage itself it still shows the (wrong) URLs coming as default with the bootstrap theme

**Comment by emilengler** [comment]
How you changed the buttons? Over the website or otherwise?

**Comment by joerg-nafcom** [comment]
By using the admin interface of the homepage of course :)

**Comment by emilengler** [comment]
What URLs do you see?

**Comment by emilengler** [comment]
Also, could you post the content of your `buttons.xml` file? That's where the button settings are stored

**Comment by joerg-nafcom** [comment]
the defaults which are https://sceneworld.org/history/external.php?name=RSS
and https://sceneworld.org/history/external.php?name=iTunes

Contents of the buttons file is 

<?xml version="1.0" encoding="utf-8"?>
<PodcastGenerator>
    <button>
        <name>RSS</name>
        <href>http://feeds.feedburner.com/SceneWorldTechHistoryInterviews</href>
        <class>btn btn-warning</class>
    </button>
    <button>
        <name>iTunes</name>
        <href>https://podcasts.apple.com/us/podcast/scene-world-tech-history-interviews/id1446267857</href>
        <class>btn btn-primary</class>
        <protocol>itpc</protocol>
    </button>
</PodcastGenerator>

**Comment by cmpilato** [comment]
@joerg-nafcom It _could_ be just a mistake with the way you pasted those contents into the issue, but there appears to be a single-quote (`'`) mark at the end of your `buttons.xml` file contents that could cause the XML parser to barf.

**Comment by joerg-nafcom** [comment]
no, that sign is not in the file, so that's not the problem

**Comment by emilengler** [comment]
Your config looks fine and works. I only get this error:
```
<itunes:category text="Society & Culture:History"></itunes:category>
```
Do you mean this?

Also if I were you I would remove the `<protocol>` line in the iTunes entry. It probably only causes errors there

**Comment by joerg-nafcom** [comment]
No the config does not work. Whatever browser I use (I even tried a different pc , i,e. while I was at work my pc in the office) and even there the URLs are the default of the theme and not what is in that file.

Attached screenshots of proof 
![Scene World Tech History Interviews - Theme Buttons - Opera_2020-01-31_23-13-03](https://user-images.githubusercontent.com/16625923/73578699-91bff300-4480-11ea-8fea-1a2fece57ec2.png)
![Scene World Tech History Interviews - Theme Buttons - Opera_2020-01-31_23-12-32](https://user-images.githubusercontent.com/16625923/73578708-984e6a80-4480-11ea-807e-e81fcaa54bfc.png)
![_2020-01-31_23-11-49](https://user-images.githubusercontent.com/16625923/73578717-9c7a8800-4480-11ea-960b-662ae4f24090.png)
![_2020-01-31_23-11-21](https://user-images.githubusercontent.com/16625923/73578721-9e444b80-4480-11ea-88c3-325996a7f161.png)

I am aware that the itunes categories are the old one, but as you can see on the links, we use feedburner to put it to itunes and for statistics, so it's not a good idea if the categories of the source podcast generator feed and the categories in feedburner mismatch.

Since Feedburner does not allow changing the categories to the new one of itunes, it is better to leave it as-is.

Regarding this, Apple Podcasts support automatically sent an email to all users using the old categories in their RSS feed to be automatically moved to another generic default category based on the seletcted obsolete one.

The protocol tag is part of the button setup as you can see on the screenshot and part of the podcast generator it seems. even if I remove it, the issue remains So since this is originating from podcast generator, hard to believe it could cause problems (if it does, maybe remove it during the update process from 2.7 to 3.x`?)
Anyway, problems of buttons not reflecting link url changes remain

**Comment by joerg-nafcom** [comment]
removing the protocol tags were a bad idea, now the whole button config got erased for both buttons :(  - bad
So the protocol tag **is** neccessary it seems

**Comment by emilengler** [comment]
Are you afraid of the `external.php` thing?
This is actually a feature rather than a bug. Still you should get redirected to feedburner don't you?

**Comment by joerg-nafcom** [comment]
Ahh I didn’t know that I’ll check and comment once I’m back from traveling tonight and let you know

**Comment by joerg-nafcom** [comment]
Now with the RSS feed no longer broken in 3.1 I can confirm it works, thanks!
