### ISSUE TITLE
paginator stopped working after podcast generator update

### ISSUE THREAD

**Issue by joerg-nafcom** [albertobeta/PodcastGenerator#209]
The paginator stopped working after podcast generator update.

I only see last 4 podcast episodes and no pager beyond page 1 despite the RSS feed and 2.7 showed over 60

even when I manually change the number of the page, e.g. https://sceneworld.org/history/index.php?page=2  this just results then in an empty page instead.

**Comment by joerg-nafcom** [comment]
perhaps a Duplicate of #187? It sounds similar to my problem

**Comment by emilengler** [comment]
What's your value of `$max_recent` in config.php?

**Comment by emilengler** [comment]
Try changing it to `"all"`

**Comment by joerg-nafcom** [comment]
it was 4, changed it to all, that worked, thanks :)

**Comment by emilengler** [comment]
No problem ;)
Be aware when changing your podcast generator config through the web interface. It happens sometimes that this value get resetted sometimes. I will fix that now

**Comment by emilengler** [comment]
3.0.1 is out now with various bug fixes.
Upgrade and see if your problem is solved now :)

Thanks,
Emil

**Comment by joerg-nafcom** [comment]
Yes it works now with the update thanks
