### ISSUE TITLE
Podcast Generator 2.6 Setup Error

### ISSUE THREAD

**Issue by i-ayush** [albertobeta/PodcastGenerator#21]
Hi, 

 I tried installing Podcast Generator 2.6 as per the instruction. The index page is displayed but there is no Textbox on the screen for Language selection. 

![error](https://cloud.githubusercontent.com/assets/5449619/22311779/1ae36760-e323-11e6-8519-4ca6097dce34.jpg)

Could you please help on this.

Thanks in advance.

**Comment by albertobeta** [comment]
Did you check the error log? Alternatively display errors on screen so you can get more feedback in regards to the missing dropdown form.
One possibility is that your server doesn't not support GETTEXT (localization), were this the case, you will hace a confirmation once you enable error log / display.

**Comment by mttaggart** [comment]
Getting the exact same error. On Ubuntu 16.04.2, PHP 7, using Nginx:

```[error] 21178#21178: *9 FastCGI sent in stderr: "PHP message: PHP Warning:  include(config.php): failed to open stream: No such file or directory in /var/www/html/podcastgen/core/includes.php on line 20
PHP message: PHP Warning:  include(): Failed opening 'config.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/podcastgen/core/includes.php on line 20
PHP message: PHP Notice:  Undefined variable: absoluteurl in /var/www/html/podcastgen/core/includes.php on line 22
PHP message: PHP Notice:  Undefined variable: absoluteurl in /var/www/html/podcastgen/core/includes.php on line 24
PHP message: PHP Notice:  Undefined variable: absoluteurl in /var/www/html/podcastgen/core/language.php on line 38
PHP message: PHP Warning:  include(config.php): failed to open stream: No such file or directory in /var/www/html/podcastgen/core/includes.php on line 20```

**Comment by albertobeta** [comment]
Thank you for pointing that out. Much appreciated. I'll look into that and propose a fix.

**Comment by adamaze** [comment]
this issue seems to be dead, but as it is still "open", I'll leave this here:

I'm seeing the same issue on:
fedora 26
PHP 7.1.10-1
apache2.4.27-3

trying to install php-gettext shows:
"Package php-common-7.1.10-1.fc26.x86_64 is already installed"
... so that doesnt seem to be the fix for me

**Comment by war6000** [comment]
I was having this same error. Found out by looking at log that i was missing simplexml, gettext and filter. I have this on a FEMP stack with php56 so for me installing this fixed it

`pkg install php56-simplexml php56-gettext php56-filter`

good luck, hope this works for someone. by the way it would be nice to have the php module requirements under Documentation>Installation>Manual

**Comment by kf4nvx** [comment]
Same issue on Ubuntu16.04/nginx/php7.0 for me. 
I installed php-xml and it worked perfectly.

**Comment by SpazShark** [comment]
Hi all - sorry I'm new to docker and trying to figure out how to fix this issue.

What specifically do I need to add to the DockerFile to install php-gettext or php7.0-xml in my podcastgen image?? I would really really appreciate some guidance!

**Comment by senarvi** [comment]
I saw the same error with PHP 7.2 and all those libraries installed. Turned out that my disk space was almost full. Saving settings would replace config.php with an empty file. This didn't issue any error, but after that all the pages would fail since absoluteurl was not defined.

**Comment by emilengler** [comment]
**Never** delete your config.php otherwise the installer will run again

**Comment by senarvi** [comment]
I didn't delete config.php. I noticed that if you have disk space almost full and try to save settings, the fwrite() deletes everything in config.php, returns 0, and leaves an empty file without issuing an error. Just wanted to point this out in case anyone else ends up here in a similar situation.
