### ISSUE TITLE
Help Wanted: Upgrade from 2.4 to 2.7 and transfering webhosts - episodes out of order

### ISSUE THREAD

**Issue by TomFaulkner** [albertobeta/PodcastGenerator#215]
Podcast Generator Version: Upgrading to 2.4 from 2.7 
Webserver: nginx
PHP Version: 7.2

I am switching web hosts, and finally switching to using Docker (https://github.com/chambana-net/docker-podcastgen). I have copied over the media directory and the categories.xml. Everything seems to be good, except the podcasts are in a different order.

Is there something I need to copy over to restore the order? I don't see a file that has the dates and times, but maybe I overlooked it.

**Comment by TomFaulkner** [comment]
Nevermind this. The dates are determined by the file timestamp. I just recopied with preserve timestamp.

**Comment by emilengler** [comment]
Yes the file order is done by the timestamp of the files.
On Unix system you can change them by this
```
touch -a -m -t 202002011827 audio.mp3
```
This would change the date to `2020-02-01 18:27`
Optionally you can add two digits at the end for seconds.
I'm currently not sure though if the parsing happens on the audio or the XML file so I would just change both
