### ISSUE TITLE
Add support for HTML5 video player

### ISSUE THREAD

**Issue by championswimmer** [albertobeta/PodcastGenerator#22]
Take a cue from this 
https://github.com/coding-blocks/bytecast.codingblocks.com/commit/46984afe3656dde7df322a87c3220f2a58d55b42#diff-ee6f2bc4e7ddcb56a474129c07618583R1075 

We could give HTML5 video player support for mp4 files

**Comment by albertobeta** [comment]
PG has support for HTML5 videos, see the [official demo](http://www.podcastgenerator.net/demoV2/pg/?name=2016-08-13_video3dprinters.mp4).

**Comment by poVoq** [comment]
@albertobeta Nice would be also support for the Podlove player:
https://podlove.org/podlove-web-player/
