### ISSUE TITLE
HTML output in <itunes:summary> tag flags a warning on feed validation

### ISSUE THREAD

**Issue by jmbarlow** [albertobeta/PodcastGenerator#23]
I'm not sure if this is a big deal, but the only issue I had with setup is a warning on the feed validation that the itunes summary should contain only plain text for maximum compatibility. I fixed this by emptying the `$allowedTags` array and commenting out the final `CDATA` encapsulation in the relevant function in `functions.php`

```php
function iTunesSummaryLinks($content) {
	$allowedTags = array("");
        // $content = '<![CDATA['.$content.']]>'; //CDATA Field
```

**Comment by albertobeta** [comment]
This will be completely rewritten in the [near future](https://github.com/albertobeta/PodcastGenerator/issues/36#issuecomment-341741130)
