### ISSUE TITLE
Feed.xml

### ISSUE THREAD

**Issue by JLF69** [albertobeta/PodcastGenerator#25]

**Comment by JLF69** [comment]
I've just added a second episode to my podcast and the feed.xml file hasn't updated.  I manually regenerated it, and the second episode appeared on the episodes page, but the rss feed still shows there as being only the original episode I started with.  Any suggestions on what I've not done/done wrong?

**Comment by albertobeta** [comment]
It looks like your feed.xml doesn't have writing permission. Try to assign them using your client (e.g. sftp client, right click on the file, info and look for "permissions"). Start with full permissions (i.e. chmod 777 -> everyone can read and write) and then try lowering them to a "more conservative" 755 and see if it works (if not, keep 777)

**Comment by JLF69** [comment]
A massive thank you mate!  I had a root around and (more by luck than any skill on my part) found the magic switch to get it working.  Again, massive thanks, its very much appreciated!!!!!
