### ISSUE TITLE
Issues with apostrophe, quotes, etc in episode names

### ISSUE THREAD

**Issue by jeremygolden** [albertobeta/PodcastGenerator#26]
Hello,
We're having issues when using special characters that break the XML feed.  We're on the the latest 2.6 version.  I was looking through the core functions code and noticed there IS a renamefilestrict, remove_accents, and renamefile which I would think should resolve the issues we're having.  However it is not working.  Is this something that has to be enabled with a setting somewhere so that the strict filenames are enforced?
Thanks!
-Jeremy

**Comment by albertobeta** [comment]
To see whether it is an issue with your server or PG 2.6, just try to use the same special characters with the official PG demo http://www.podcastgenerator.net/demoV2/
if it works there, you are 100% it is a server side issue you are experiencing (probably encoding). In the the former case, bouble check and make sure you have UTF8 encoding enabled (e.g. check your server config, such as php.ini etc...). In the latter case, please let me know and we'll fix.

**Comment by jeremygolden** [comment]
The demo site worked however it still was causing me issues.  I finally got it working on IIS (Windows 2008 R2) with PHP 7 (Installed by the Web Platform Installer) by the following 2 changes:


  1.  From https://docs.moodle.org/30/en/Internet_Information_Services I added the reg key: reg add HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\w3svc\Parameters /v FastCGIUtf8ServerVariables /t REG_MULTI_SZ /d REQUEST_URI\0PATH_INFO

  2.  From https://allseeing-i.com/How-to-setup-your-PHP-site-to-use-UTF8 I confirmed mbstrings was enabled and added the following to core\includes.php:

//setup php for working with Unicode data
mb_internal_encoding('UTF-8');
mb_http_output('UTF-8');
mb_http_input('UTF-8');
mb_language('uni');
mb_regex_encoding('UTF-8');
ob_start('mb_output_handler');



#1 did not appear to fix it as I still had issues later but I believe #2 may have finally resolved the issue.

Thanks,

Jeremy Golden
[cid:image001.png@01D1FD5F.05FE08F0]
303.722.7668  ⬛  www.GrahamGoldenTech.com<http://www.grahamgoldentech.com/>
