### ISSUE TITLE
Null Response on Submitting via iTunes Link

### ISSUE THREAD

**Issue by cogdog** [albertobeta/PodcastGenerator#28]
I was unable to submit my podcast feed to iTunes store via the admin link, repeatedly the response in iTunes was

![null](https://user-images.githubusercontent.com/463038/30777799-2f8a6fb6-a078-11e7-90ce-d9abc8d6e474.jpg)

I was able to submit directly via https://podcastsconnect.apple.com/ and it picked up all the info correctly from Podcast Generator.

**Comment by albertobeta** [comment]
Hi, 
the process to submit your podcast to iTunes changed (I will soon remove that link from Podcast Generator admin interface), now you have to follow these instructions:
https://medium.com/create-buzz/submitting-your-podcast-to-itunes-using-itunes-connect-22b95b38068d

**Comment by albertobeta** [comment]
[fixed](https://github.com/albertobeta/PodcastGenerator/commit/7e29b8d284b2966db80507488af56fbd8ee44bb5)
