### ISSUE TITLE
Feature request: Add possibility to specify image for each episode

### ISSUE THREAD

**Issue by alwa** [albertobeta/PodcastGenerator#30]
According to http://www.itunes.com/dtds/podcast-1.0.dtd it is possible to specify an image for each item (episode) using the tag itunes:image. 

I think that it would be a great enhancement if an image can be set, not only for the podcast as a whole, per episode.

**Comment by albertobeta** [comment]
Yes it is possible. you just have to embed the image in the episode as "cover art" using iTunes. The image will be extracted and will appear automatically with the tag itunes:image
Try upload the attached file to PG and you'll see (unzip it before uploading it).
[2013-04-11_m1.mp3.zip](https://github.com/albertobeta/PodcastGenerator/files/1522547/2013-04-11_m1.mp3.zip)

Stay tuned :) A brand-new and more modern version of Podcast Generator is expected in early 2018. [Read more](https://github.com/albertobeta/PodcastGenerator/issues/36#issuecomment-341741130)

**Comment by alixwar** [comment]
@albertobeta Very nice! Worked like a charm. Will read your post! One question: Is there a simple way to re-upload an old episode with the cover art without breaking Podcast generators indexing based on dates, etc?

That is to fake that the old episode with the cover art is still the old episode and nothing new

**Comment by alwa** [comment]
@albertobeta Very nice! Worked like a charm. Will read your post! One question: Is there a simple way to re-upload an old episode with the cover art without breaking Podcast generators indexing based on dates, etc? That is to fake that the old episode with the cover art is still the old episode and nothing new

**Comment by albertobeta** [comment]
there is no direct way, if you replace the old file with a new one embedding cover art, PG won't know  it so the image won't be extracted... The only way to extract a cover art is to upload explicitly the episode via PG

**Comment by alwa** [comment]
Okay, good to know! Thanks!

**Comment by alwa** [comment]
@albertobeta I don't know why but I no longer see the preview image for newly uploaded episodes. Is there is some kind of implicit requirements on the cover art? If I open the mp3 locally with iTunes then the cover art is there but it's not shown in neither PG or iTunes. I've tried PNG and JPG, from 1400x1400 to 3000x3000. Is there anything else that you know must be there to be accepted?

**Comment by alwa** [comment]
I found a work-around. If I upload an image that corresponds to the episodes name after indexing to the folder: "images" then the cover art shows up in Podcast Generator for the episode
