### ISSUE TITLE
Comment add for the single podcast page

### ISSUE THREAD

**Issue by StingerHU** [albertobeta/PodcastGenerator#32]
Is it possible to somehow add a code for single podcast page like disqus ? It would be great to invite a javascript addon like this - in this case we don't need to put extra lines for maintain a database...

**Comment by albertobeta** [comment]
Yes you can! it's a hidden feature:
IF a file called embed-code.txt is manually created in the root of Podcast Generator. The content of that file will be displayed along with each episode.

See [here](https://github.com/albertobeta/PodcastGenerator/blob/f9678745c9ca213d543adb24d17a23ba7cceef07/core/functions.php#L1490).
