### ISSUE TITLE
Warning: date(): It is not safe to rely on the system's timezone settings.

### ISSUE THREAD

**Issue by c4uran** [albertobeta/PodcastGenerator#34]
podcastgen 2.6 on synology dsm 6.1

full text of error:
Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /volume1/web/podcastgen/core/functions.php on line 504 Warning: date(): It is not safe to rely on the system's timezone settings.

![screen shot 2017-10-18 at 12 44 11](https://user-images.githubusercontent.com/12890369/31711838-1475fdf6-b402-11e7-92c2-c5cac5a3f091.png)

**Comment by ijg** [comment]
Check your php.ini file, ensure you have your local timezone specified in there, otherwise you'll get this error and the timezone will default to utc.  You should have this in your file somewhere:

`[Date]
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = America/New_York
`

**Comment by c4uran** [comment]
i checked php.ini on /usr/local/etc/php56/php.ini

p.s before i dont have that notification on podcastgen

![screen shot 2017-10-19 at 16 51 37](https://user- images.githubusercontent.com/12890369/31774242-db129ca8-b4ed-11e7-8d12-522b98a0aa22.png)

**Comment by c4uran** [comment]
okay i tryed almost everything like reinstall php56 and podcastgen nothing work at all

added in functions.php:
date_default_timezone_set('Europe/Moscow');

now work fine but i dont know its right solution?

**Comment by ijg** [comment]
This will work, but when you update the software you'll lose the functionality.

Are you sure you're updating the correct php.ini file?

If you know how to do this,  hope you don't take offense, but if not..
create a file called 'test.php' with one line in it:

<?php phpinfo(); ?>

Then load it via your website.  It will show you the location of the PHP ini file being used.  There may also be a local one over-writing the global one.

If your addon works in functions.php, but not in php.ini it would suggest there may be more than one ini file on your system, and the one you're editing isn't the 'active' one.

Hope this helps.

ig.

**Comment by c4uran** [comment]
used find and got
./etc/php/php.ini
./etc.defaults/php/php.ini
./usr/local/etc/php56/php.ini
./usr/local/etc/php70/php.ini
_./usr/syno/etc/packages/WebStation/php56/php.ini
./usr/syno/etc/packages/WebStation/php70/php.ini_
./volume1/@appstore/PHP7.0/usr/local/etc/php70/php.ini
./volume1/@appstore/PHP5.6/usr/local/etc/php56/php.ini

except ./usr/syno/etc/packages/WebStation/*

have that string, but web station php is synology dsm system php 

i dont know how to find right php file or file override preference of default php

**Comment by albertobeta** [comment]
It's a warning and not an error. It is probably due to synology default config. If PG works fine you could just disable the warning display so you wouldn't see it, otherwise you have to make custom changes to the PHP.ini as explained above.
