### ISSUE TITLE
Podcast Date and time

### ISSUE THREAD

**Issue by ijg** [albertobeta/PodcastGenerator#35]
I'm having a strange issue when I try to upload a back dated podcast, say from July 1st. 2017.  I fill in all the fields as expected, but the upload has today's date as the file name, eg.  2017-10-20_test.mp3 and even if I go in and edit the information, it says it's updating but nothing changes and there are no errors.   This has also affected the sort order when the files are displayed.  I went in and manually changed the filename and xml filename to the proper date, but they still all appear with today's date and I can't sort them.  Very strange.  Any help appreciated and thank you.

**Comment by albertobeta** [comment]
Yes, it works as designed. When you upload a podcast in some cases you cannot specify a past date. See also https://github.com/albertobeta/PodcastGenerator/issues/42
