### ISSUE TITLE
FAQ on Disable iTunes notification doesn't match the current UI

### ISSUE THREAD

**Issue by LwsBtlr** [albertobeta/PodcastGenerator#37]
When trying to follow the FAQ[1] to disable listing a podcast on iTunes, the steps do not match the current UI. I've not been able to find the settings to prevent any interaction with the iTunes podcast directory.

[1] http://www.podcastgenerator.net/documentation/FAQ-itunes-remove

None of step 1-4 match the UI I see on my synology after installing the package and setting up a test podcast.

**Comment by albertobeta** [comment]
You're right. Now podcasts are handled via http://itunesconnect.apple.com
I'll update the FAQs. Thanks

**Comment by albertobeta** [comment]
fixed
