### ISSUE TITLE
New episodes showing up as 0MB

### ISSUE THREAD

**Issue by jbrierton** [albertobeta/PodcastGenerator#39]
Hello,
We've been using your platform for a year and love it. Although we've recently run into a snag and I'm hoping you can help. All newly uploaded episodes via FTP are showing as 0MB inside Podcast Generator.

The files on the FTP are fully uploaded. I can see them on the FTP server themselves. However when I try to index them into Podcast Generator, Podcast Generator generates an episode, but the file is 0MB.

I've tried removing faulty episodes, re-uploading, etc etc. Nothing seems to work.

Uploading through Podcast Generator works but our shows are typically an hour and larger than 50 MB. 

Any support you can give would be greatly appreciated. Thanks for providing the platform!

-James

**Comment by albertobeta** [comment]
Hello,
glad you like PG :)
This is an unknown issue and it might depend on your server and on the way you upload via FTP (e.g. binary Vs ASCII mode). If you need specific help you can always ask the [premium support](http://www.podcastgenerator.net/support). 

Stay tuned :) A brand-new and more modern version of Podcast Generator is expected in early 2018. [Read more](https://github.com/albertobeta/PodcastGenerator/issues/36#issuecomment-341741130)

**Comment by jbrierton** [comment]
Thanks, Alberto. Excited to see the 2018 updates.

I'm adding in Jared Smith. He works on our podcast and has an extensive,
technical background. He suggested something similar regarding FTP settings
and modes. We'll look into that further. It was certainly strange that it
worked for awhile and then suddenly stopped.

In the meanwhile, I've taken to compressing down to 50 MB and uploading via
the browser. That seems to have at least gotten the show back online.

Thanks for your note. Please do keep in touch if you think of anything new.
We'll do the same: If we manage to solve it, we'll let you know what we did.

**Comment by albertobeta** [comment]
Great!
