### ISSUE TITLE
Podcast Timezone

### ISSUE THREAD

**Issue by FrankandOzz** [albertobeta/PodcastGenerator#40]
Hey,

Thanks for Podcast Generator! It seems like a great tool that makes podcasting easy and we're very happy with it so far.

One minor problem I'm having is that podcast generator seems to be stuck in the timezone I used when setting it up and I can't seem to change it. This causes a bit of confusion when scheduling episodes to go live ahead of time. I've had a root around in the files but can't find anything obvious to change.

Some help with this would be greatly appreciated.

Cheers!

Frank

**Comment by hetzbh** [comment]
IIRC Podcast Generator reads the time zone from PHP, so you'll need to change in the php.ini file. see [this](http://www.inmotionhosting.com/support/website/php/setting-the-timezone-for-php-in-the-phpini-file) for example.

**Comment by FrankandOzz** [comment]
That did it. Thanks!
