### ISSUE TITLE
Soundcloud RSS feed

### ISSUE THREAD

**Issue by stephangriesel** [albertobeta/PodcastGenerator#41]
I have changed my feed_url replace config with my SoundCloud RSS url. How can I get the episodes to display on my Podcast Generator? I can see the RSS is showing to my SoundCloud but not getting the episodes to show.

**Comment by albertobeta** [comment]
Soundcloud is an alternative to PG. [Changing the default URL of the podcast feed](http://www.podcastgenerator.net/documentation/FAQ-change-RSS-URL) in PG is just for statistic purposes, but it doesn't mean you use an alternative service and the podcast appear in PG (i.e. better to choose either Soundcloud or PG)
