### ISSUE TITLE
Problem with the back-dated uploads

### ISSUE THREAD

**Issue by bisherbas** [albertobeta/PodcastGenerator#42]
When I upload an old episode, I choose the date from the drop-down menu. However, when the upload is finished, the episode date becomes today's date. I end up needing to modify the date after the file is uploaded. Is there a solution to this problem? I have got hundreds of old episodes to upload and I do not wish to edit all of these episodes after they are uploaded.

![Screenshot](https://i.imgur.com/VvVERA0.jpg)

**Comment by albertobeta** [comment]
Unfortunately the episode date is always the upload date, and you can change the date retroactively later. 
If you have hundreds of episodes you could write an automatic script that parse the file date in the file name (I suppose you have the date in the file name) and changes it ("touch" command) recursively for all your old files. It could take a while (alternatively, ask to [premium support](http://www.podcastgenerator.net/premium-support)) to write the script but it would save you the manual work of changing dates one by one after the upload.
