### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by danieledirubbo** [albertobeta/PodcastGenerator#46]
Is there a way to change the favicon of our website powered by Podcast Generator?

**Comment by albertobeta** [comment]
Sure, just replace the [favicon file](https://github.com/albertobeta/PodcastGenerator/blob/master/favicon.ico) with any file you want.
If you need help generating the favicon, this is [a nice free service](http://www.favicomatic.com/).

**Comment by danieledirubbo** [comment]
Thank you!
