### ISSUE TITLE
Predated episodes shows up on today‘s date

### ISSUE THREAD

**Issue by danieledirubbo** [albertobeta/PodcastGenerator#47]
I noticed that we can put a future date and so schedule the episode to be released at a future date, and that’s OK.

However, another thing I noticed is that, if I predate an episode, it is published in the current day and hour and I have to change it manually only in a second moment.

Is there any means to avoid that?

**Comment by albertobeta** [comment]
Not worth to tackle this issue now, but I'll improve in the [future major version](https://github.com/albertobeta/PodcastGenerator/issues/36#issuecomment-341741130).
