### ISSUE TITLE
How to transfere here a podcast already existing

### ISSUE THREAD

**Issue by paolombaro** [albertobeta/PodcastGenerator#49]
I'd like to transfer an existing podcast who is two Years old.
Now is not working because iTunes refused it,  They say that RSS Feed is not Working properly, but I didn't Change anything  and now I can't Fix It
I'd Like To transfer the podcast using podcast Generator without Losing my ranking and my History. 
What should I do? 

Thank you very much to everyone could Help me.

I'm very Sorry For My English But I'm italian. 
Bye 
Paolo

**Comment by albertobeta** [comment]
PG doesn't offer an import option from other feeds yet, I'd love to offer this option in future. In the meanwhile, if you don't code, you can ask to any developer (friend or professional) to do that for you. You need a custom program that, given a RSS feed (i.e. your old podcast) can import it directly in PG.
In bocca al lupo!
