### ISSUE TITLE
iTunes link doesn't seem to be correct

### ISSUE THREAD

**Issue by bts368** [albertobeta/PodcastGenerator#5]
even in 2.5, the themes don't seem to work correctly with regards to my iTunes button.

I run https://sysadministrivia.com. The iTunes button keeps generating as https://sysadministrivia.com/feed.xml (it won't appear to- I've switched back to my custom theme, where it's hardcoded in)

I believe this should be either itpc://sysadministrivia.com/feed.xml
OR
https://itunes.apple.com/us/podcast/sysadministrivia/id969859929
(as we are on the iTunes store).

Please make a configuration option to allow to override the URI for this button, as I'd like it to point to our entry in the iTunes store- what's the point if it just points to the same URI as the "RSS Feed" button?

**Comment by albertobeta** [comment]
I just checked out https://sysadministrivia.com with the default modern theme and RSS & iTunes buttons seem to work fine.
If you have a custom theme, it's just a matter of hard coding the iTunes store URL if you want a quick fix.
In generale, there is also a hidden feature so that, in config.php you specify `$podcastFeedURL="customURL"` this will replace the default URLs.

**Comment by bts368** [comment]
"I just checked out https://sysadministrivia.com with the default modern theme and RSS & iTunes buttons seem to work fine."

As I said, I just manually edited the theme to hardcode it in there.
`[root@alpha default_modern]# sed -i -e 's|-----PG2_URLFORITUNES-----|https://itunes.apple.com/us/podcast/sysadministrivia/id969859929|g' index.htm`

If I don't, it uses https://sysadministrivia.com/feed.xml for BOTH the RSS Feed and iTunes button.

"If you have a custom theme, it's just a matter of hard coding the iTunes store URL if you want a quick fix.
In general, there is also a 'hidden' feature so that, if in config.php you specify $podcastFeedURL="customURL" this will replace the default URLs."

Right, and that's well and dandy, but it's not the RSS feed I'm worried about- it's the iTunes button's URL.  In other words, one should be able to set $podcastFeedURLiTunes in config.php (just as they can set $podcastFeedURL). I tried doing this but it made no difference (and, in fact, was removed when I hit save in the "Change Podcast Generator Configuration" page).

**Comment by bts368** [comment]
(To further clarify- one should be able to manually specify different URLs for the different buttons)

**Comment by albertobeta** [comment]
Ok. It makes sense. I just did it [https://github.com/albertobeta/PodcastGenerator/commit/b10e9954712e65036abdb5a044a0c3408a42e63f]. Download the latest version of core/templates.php from the repo and specify `$feed_iTunes_URL_replace` in your config.php. Please test it (I didn't test it yet) and confirm it works.

**Comment by albertobeta** [comment]
PS. Also download the latest commit of /core/admin/createconfig.php [https://github.com/albertobeta/PodcastGenerator/commit/34e1b8a8557eca293abcec9b9be55cf07cd2aaea] so that the change in config.php is preserved when you regenerate PG configuration.

**Comment by bts368** [comment]
you had it fixed before i could even reply. :) looks like it's all working perfectly now. thank you! now i can remove the sed line from my upgrade script :) cheers!
