### ISSUE TITLE
sudden errors are creating a fatal error

### ISSUE THREAD

**Issue by pastortroy** [albertobeta/PodcastGenerator#51]
Any help in diagnosing what is going on would be appreciated. We have been using podcast generator for years with little to no issues. The files mentioned in the error are in their rightful place, can't figure out why this happened all of a sudden.

www.tcfchurch.org/podcastgenerator/

**Comment by albertobeta** [comment]
It's probably an issue with your server/hosting. Contact [PG premium support](http://www.podcastgenerator.net/premium-support) if you need custom help.
