### ISSUE TITLE
I can't upload new episodes of my podcast.

### ISSUE THREAD

**Issue by rjwilliams22** [albertobeta/PodcastGenerator#52]
Hello,

I've uploaded 5 episodes of my company's podcast with your tool and everything worked perfectly, but when I try to upload the 6th episode nothing happens. I can make edits to the episodes that are already apart of the RSS feed. but I can't add another episode. 

When I fill out all of the required fields and click the "Upload Episode" button, I get a loading pop-up that runs for a couple minutes. After that, the screen goes white with the URL like the one below. 

mywebsite.com/podcastgen/?p=admin&do=upload&c=ok

Any assistance would be greatly appreciated.

**Comment by albertobeta** [comment]
It's probably an issue due to lack of writing permissions in your server. You need to set writing permissions (e.g. chmod 777) to the folder containing PG and all the file and folders contained.
