### ISSUE TITLE
Podcast are out of order after migrating site

### ISSUE THREAD

**Issue by madre8** [albertobeta/PodcastGenerator#53]
I have tried and failed several times to migrate an podcast generator to a new site. What I've tried so far is installing a new upload of PG to the new site, then uploading via Filezilla all the media files, the feed.xml, and the categories.xml files from the old site. Once I refresh the homepage after doing that, all the podcasts (sermons) have the same publish date and are all out of order. I've also tried following directions for doing an upgrade, but got the same results. Am I missing a step? Is there a way to keep the published dates and order of the sermons without having to manually go in and edit the dates in the feed.xml file? There are a few hundred sermons!!!
Thanks!
Amelia

**Comment by albertobeta** [comment]
See here: https://github.com/albertobeta/PodcastGenerator/issues/59
