### ISSUE TITLE
Cannot upload episodes via FTP

### ISSUE THREAD

**Issue by kldudeck** [albertobeta/PodcastGenerator#54]
It may be because I am totally bleary-eyed right now, but I cannot for the life of me figure out how to FTP the podcast episode. It's an hour long and roughly 20MB, and since my hosting company limits uploads to 2MB, I have to FTP. Yes, I know it's a totally newbie question, but I'm giving in and posting :) Thanks for any help.

**Comment by albertobeta** [comment]
upload your episode into the "media" folder using an FTP client. Then just run "FTP Feature (Auto Indexing)" from the admin area of PG

**Comment by kldudeck** [comment]
Thank you! Trying it out now...
