### ISSUE TITLE
Long and short descriptions in iTunes/iOS podcast app

### ISSUE THREAD

**Issue by JLF69** [albertobeta/PodcastGenerator#55]
Hi, the long and short descriptions seem to be reversed when viewed in either the MacOs or iOS podcast app.  Is this just an Apple thing perhaps?

**Comment by marek90** [comment]
Hi. I can confirm. Is there any fix? Thanks.

**Comment by albertobeta** [comment]
Noted down thanks. Will investigate and fix in a future version.
