### ISSUE TITLE
auto generate xml feed for scheduled episodes

### ISSUE THREAD

**Issue by rivadoza** [albertobeta/PodcastGenerator#56]
Hello,

Thanks for PG and your work.

Are-there any possibilities for that a scheduled episode can be automaticaly added in the feed.xml ?

I may place a cron task, but what would be the command ?

Thank you

CJ

**Comment by albertobeta** [comment]
yes, cron support comes out of the box with PG :)
Go to Admin -> Change Podcast Generator Configuration
You'll see the cron command which includes your unique key.
See also
http://www.podcastgenerator.net/documentation/FAQ-cron-job
