### ISSUE TITLE
Back dating episodes (setting a Publication Date that's in the past, when uploading)

### ISSUE THREAD

**Issue by davidprosser** [albertobeta/PodcastGenerator#57]
I use Podcast Generator to manage our church's preaches, of which there's one every Sunday. 

Sometimes I don't get round to uploading it until early in the week, but it's helpful to set the date as that of the previous Sunday. 

If I do this using the "Publication Date" option it never saves it - I always have to upload with today's date, then go to All Episodes, Edit, and then change the date to backdate it. 

Would it be possible to allow the Publication Date field to work in the past, too?

**Comment by albertobeta** [comment]
That's true. 
Backdate when uploading is not working since the file timestamp can be changed (or "touched") just after the upload. 
This is a missing feature for future improvements.
