### ISSUE TITLE
FTP upload on Synology does not appear to work

### ISSUE THREAD

**Issue by dscottfrey** [albertobeta/PodcastGenerator#58]
I'm trying to upload very large files (audiobooks) to PCG on a Synology using the installed package provided in Package Center. 

1) File upload limit seems to be stuck at 32MB no matter where I change it in php.ini or Web Station. 

2) Uploading a file to the /volume1/@appstore/PodcastGenerator/podcastgen1.4/media folder and telling it to scan in the FTP Upload feature results in not finding any files. As far as I can tell, the "media/" folder is at /volume1/@appstore/PodcastGenerator/podcastgen1.4/media

Solving either of these would make it work

**Comment by albertobeta** [comment]
You should get in touch with Synology and ask how to increase the Upload Max Filesize for a PHP script, see also here:
http://www.podcastgenerator.net/documentation/FAQ-max-upload-size
They should be able to provide you with instruction on how to do that (e.g. maybe they overwrite PHP.ini with some other config files that you can change via the Synology control panel)
