### ISSUE TITLE
Setting Timezone

### ISSUE THREAD

**Issue by schultzie86** [albertobeta/PodcastGenerator#61]
Not sure if I'm missing something here - is it possible to change the timezone that is used? Since I couldn't find a setting anywhere, I assumed it was getting the timezone from the hosting server - I have tried adding our timezone to the .htaccess file but that hasn't made a difference. At the moment I'm manually editing the feed.xml file each time I upload a new episode. Thanks!

**Comment by albertobeta** [comment]
Hi, the timezone is taken directly from the server configuration and there is no explicit setting for that.
If you have your own server, just change it there or contact your hosting provider for more information in case you use a shared hosting (they probably don't allow you to overwrite the timezone via .htaccess)
