### ISSUE TITLE
(Newer) QNAP Version Available?

### ISSUE THREAD

**Issue by nunnsby** [albertobeta/PodcastGenerator#63]
I have in the past installed a version of Podcast Generator (podcastgen) from the Official QNAP App Center on my QNAP. It has never worked and in all fairness is version 1.0 from 2014. 

Is there a newer version available for QNAPs?

From the App:
Podcastgen is a open software made for uploading, hosting, and synching mp3s,mpgs,Movs, and many other media file types . It also has a feature to link up to iTunes and easy downloads.
Language:
English, 简体中文, 繁體中文
Developer: http://podcastgen.sourceforge.net/
Maintainer: MITLAB_Tien

The links I have from the app are: 

Download: https://download.qnap.com/QPKG/podcastgen_1.0.zip
Forum: http://podcastgen.sourceforge.net/
Change Log: https://www.qnap.com/_jump/releasenotes/app.php?app_choose=podcastgen

Screenshot of app attached:

![image](https://user-images.githubusercontent.com/9913478/37569464-acf137a4-2ada-11e8-80ca-2954154ecedd.png)

**Comment by albertobeta** [comment]
that version is so old that it should be even available in QNAPs :/
Why don't you download the latest version (highly recommended!) and install it manually?
