### ISSUE TITLE
Download completed but then what?

### ISSUE THREAD

**Issue by bfdanaher** [albertobeta/PodcastGenerator#64]
I am downloading the podcast generator, but cannot find the file to start the installation process. The ReadMe is not recognized on my iMac. Do you support iMac?

**Comment by albertobeta** [comment]
Nope. PG is a web-based application that needs to be [installed on a web server](http://www.podcastgenerator.net/documentation/installation#manual) to work.
Once installed, it will look like this: http://www.podcastgenerator.net/demoV2/
In case you don't want to deal with installation and technicalities, PG is also available as a f[ully managed service with a monthly subscription](http://www.podcastgenerator.net/documentation/installation).
