### ISSUE TITLE
Sort Functionality when Manually Creating Feed post "FTP Upload"

### ISSUE THREAD

**Issue by nunnsby** [albertobeta/PodcastGenerator#66]
I would love to be able to specify a sort function when creating the feed.xml file. 

I upload a lot of files to populate the media, and they are numbered:
file-01
file-02
file-03
 ... 
file-30

But when creating the feed.xml file, it appears to randomly add them to the file. It may go 30,29,28,25,27,26,20,24,etc. Every time is pretty random. I guess it has to do with time stanps and file sizes maybe, not sure.

I would love to be able to say create feed sorted by filename in order, or in reverse.  

The only way for me to fix it for the podcast app on my phone is to go in and manually edit the feed.xml file, and fiddle with the timestamps/publishing time of the file. 

Also, if I do manipulate the feed file, it does not change the podcast page display.

So I reorder the feed.xml file and have it go 30 - 01 fine. But, the page will still display the episodes as 30,29,28,25,27... etc.

Anyway, great work, thanks a lot. A small bit of admin on my side is now allowing me to take my custom audio and video with me without have to use iTunes, so totally appreciate it. :)

**Comment by madsha** [comment]
I would be very interested in this function, too
My files are like this
0 Intro.mp3
00 List of contents.mp3
001 Some file name.mp3
002 Some other file name.mp3
...
029 Outro.mp3

The files name have spaces in them, and may have punctuation - !&,.)( - and the danish letters æøå, ÆØÅ but will always start with a number followed by a space.

Great work, thanks a lot!

**Comment by IsidoreIsou** [comment]
I have exactly the same problem ! Would love to find a solution.
