### ISSUE TITLE
Fatal Error with Quciktime.php module when attempting to manually add file via FTP 

### ISSUE THREAD

**Issue by jfischetti22** [albertobeta/PodcastGenerator#69]
I get the following error when i try to search for new files in my FTP directory.

Its seems it's a large file error, but i have many files larger than this one that have easily been found by the Manual FTP process.

Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 3820977 bytes) in /data/46/1/15/129/1178944/user/1253493/htdocs/podcast/components/getid3/module.audio-video.quicktime.php on line 1438

Any ideas on how to get around this.   It worked the first time i uploaded this particular file, but it had an editing issue, so when i tried to add again, i got this error.

**Comment by albertobeta** [comment]
your hosting (probably a shared hosting space) is limited, you might want to contact your provider and ask
