### ISSUE TITLE
upload_max_filesize (php.ini) stuck at 32M 

### ISSUE THREAD

**Issue by ridgers** [albertobeta/PodcastGenerator#70]
I've edited my php.ini file and set both upload_max_filesize and post_max_size to 64M yet I still can't upload a file larger than 32M.

The exact error message I get when I try to upload a file of 50MB is 'Error: No file, description or title present' There is a title and description int he upload form.

I'm wondering if maybe this is a permissions issue? This all seems to have started around the time Synology released DSM 6. Prior to 6, editing these setting allowed me to upload larger files. DMS 6 seems to have had a number of file permission changes.

**Comment by albertobeta** [comment]
yes, it seems to be a server issue. Make sure the media folder and all its contents have writing permission (try "CHMOD 777)

**Comment by pettedemon** [comment]
Hi,
same problem with php 7 even if the media folder is 777.
thanks

**Comment by nkomarov** [comment]
no problem with cPanel. Just went to MultiPHP INI Editor - done.
