### ISSUE TITLE
mp3 not a supported extension

### ISSUE THREAD

**Issue by jskvbinmv** [albertobeta/PodcastGenerator#71]
A while ago creating new episodes on 2.6 failed with the following message:

> Processing episode...
> 
> Original filename: test.mp3
> 
> mp3 is not a supported extension or your filename contains forbidden characters.

Today I tried again with a new install of Podcast Generator 2.7 but it still gives me the same error. As far as I know I didn't change anything. 

Can someone help me with what to fix for being able to upload files again?

**Comment by albertobeta** [comment]
Try to reinstall PG, you might have some corrupt or missing files (e.g. the XML file with the accepted file extensions). From your example your file name was "test.mp3", correct? If not, make sure the file name uses only A Z characters just to exclude this possible issue

**Comment by jskvbinmv** [comment]
A fresh install still gives the same error. I tested

test.mp3, TEST.mp3 and TEST.MP3

all fail with the same error message.

I did however notice, on the first setup page I'm not able to select languages. The dropdown is empty, maybe some files aren't found ... i don't know.
