### ISSUE TITLE
Delay posting episode detected through "FTP Auto-Indexing"

### ISSUE THREAD

**Issue by eladavron** [albertobeta/PodcastGenerator#74]
So FTP Auto Indexing is a great feature, but I don't want the episode to actually post until after I've edited it to add description and tags and stuff. Is there a way to have it generate an episode buy delay posting it by like 15 minutes?

**Comment by albertobeta** [comment]
yes, you can upload files to the media folder without index them manually but use the CRON feature of PG 
http://www.podcastgenerator.net/documentation/FAQ-cron-job
