### ISSUE TITLE
Trouble Installing Version 2.7

### ISSUE THREAD

**Issue by CSema2959** [albertobeta/PodcastGenerator#75]
Similar to the issue with 2.6, I am unable to continue with setup. Could someone lend some help?

Thanks! 
![podcast](https://user-images.githubusercontent.com/36346842/39336892-d00d23f8-4987-11e8-80d2-5b50bddb750f.PNG)

**Comment by CSema2959** [comment]
I was able to solve my problem. If anyone else runs into this, how I resolved is below. ( All commands below are run as root)

1- apt-get update
2- tail /var/log/apache2/error.log - to verify the problem (which was the locale setting, simplexml not loaded and gettext)
3- Under /var/www/html/ add info.php and put the following content inside 
   3A- <?php
          phpinfo();
          ?>
4- Navigate to your url /info.php and find your loaded config file
5- vi to your loaded config and verify your locale setting.
6- Install gettext = apt-get install gettext
7- Set locale for UTF-8 = locale-gen sv_SE.UTF-8
8- Restart Apache2 = service apache2 restart
9- Add repository to PHP7 = add-apt-repository ppa:nijel/phpmyadmin
10- Update the box again = apt-get update
11- Restart Apache2 = service apache2 restart
12- Install remaining simplexml and extra's = apt install php7.0-mbstring php7.0-zip php7.0-xml
13  Again, Restart apache2 and see if it fixes your problem =  service apache2 restart

**Comment by Mikee-3000** [comment]
Same thing happened to me on nginx + php7.2-fpm + ubuntu18.04 . Thanks to the above post and thanks to https://stackoverflow.com/questions/35593521/php-7-simplexml I was able to fix it with a simple 
```
sudo apt install php7.2-xml
sudo systemctl restart nginx
sudo systemctl restart php7.2-fpm.service
```
