### ISSUE TITLE
Feed keeps old IP after change of Synology's IP address

### ISSUE THREAD

**Issue by cactux** [albertobeta/PodcastGenerator#77]
I had to change the IP of my Synology, but podcast generator keeps using the old IP address in the feed. I can still access the admin pages, add or remove mp3 files to the feed, but the feed stays on the old IP address.

**Comment by albertobeta** [comment]
check config.php to make sure you don't have the old IP address

**Comment by cactux** [comment]
Yes, that did it, I forgot to post an update here. Thanks.
Do you think it should be possible to do it from the admin web page? It would be cool.
