### ISSUE TITLE
Excessive pages in pagination block when viewing first page of an archive category

### ISSUE THREAD

**Issue by cmpilato** [albertobeta/PodcastGenerator#82]
When filtering podcasts to only those which match a particular category (that is, with a URL similar to `http://podcasts.example.com/?p=archive&cat=some_category`), I find that the pagination block at the bottom of the first page contains far, far more pages than are required to present all the podcasts for that category.

In my case, I have 13 podcasts in a particular category:  10 on page 1, 3 on page 2.  Yet page 1 of the display shows a whopping 40 pages to select from.  Now, if I select page 3 or higher, I'm presented with an empty set of podcasts, and the pagination block correctly contains only 2 pages.  If I select page 2, I see the 3 podcasts I expect to see, and again the pagination block has 2 pages.  But if I then return to page 1, I see the 10 expected podcasts and, again, 40 page links in the pagination block.

This problem occurs using multiple themes, so doesn't appear to be theme-specific.

**Comment by albertobeta** [comment]
it could be a bug. Thanks for pointing it out.

**Comment by cmpilato** [comment]
Why was this closed without any additional status update?

**Comment by emilengler** [comment]
This is because Podcast Generator Version 3 is getting released tomorrow (31th of December).

Because PG3 has a complete new codebase, all the old bugs shoudn't be there.

Sorry for closing this but givinig support for an old version would make no sense.

**Comment by cmpilato** [comment]
Ah, that's good news!  Does PGv3 offer an easy migration path from this older version?  If so, I look forward to upgrading.

**Comment by emilengler** [comment]
> Ah, that's good news! Does PGv3 offer an easy migration path from this older version? If so, I look forward to upgrading.

Except from themes, PG3 is fully backwards compatible with the config and episodes. You can use it as before :-)
