### ISSUE TITLE
podcast statistics using podtrac

### ISSUE THREAD

**Issue by madsha** [albertobeta/PodcastGenerator#86]
Is the info at
http://www.podcastgenerator.net/documentation/FAQ-change-RSS-URL
still up to date?

It mentions in the section about podtrac to make this sort of change:
$feed_URL_replace = "http://podtrac.com/yourAccount?".$url.$feed_dir."feed.xml";

But I can't figere out how to get it working. 
For one thing, I'm not sure what "yourAccount" should be - I don't see anything called that, when I log into podtrac.com. There IS a unique string of numbers and letters in the address line, when I navigate arounf podtrac.com. I tried inserting that string, remembering the trailing ?, but it didn't seem to do anything.

I'm probably overlooking something basic here, so any help will be highly valued :-)
/Mads Hansen

**Comment by star104** [comment]
I just signed up for podtrac also and cannot figure out what I'm supposed to do either.  I assume the only way this works is for to change the name of your REAL xml to "feed2.xml" and redirect the original feed.xml to podtrac.

**Comment by madsha** [comment]
Hi star104

It turns out, that you have to get the podtrac redirect into the enclosure url.
Alberto instructed me, how to make a change (hack) in /core/functions.php, line 1387:

The original line reads:
<enclosure url="'.$url.$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>

Change it to (still all on one line)

<enclosure url="'."http://dts.podtrac.com/redirect.mp3/kkb-lyd.dk/maanedens/".$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>

Put in your own url instead of kkb-lyd.dk/maanedens of course

This worked for me - and I couldn't have done it without Albertos help, coz I'm no programmer!

Hope this helps,

Mads Hansen

**Comment by madsha** [comment]
...

The original line reads:
<enclosure url="'.$url.$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>


...

**Comment by madsha** [comment]
...
it won't let me put that in...
Well, it's line 1387
...

**Comment by star104** [comment]
I just realized this won't work, because I changed my podcast from mp3 to aac recently, so there's no way to do both formats :(

**Comment by radiostorm** [comment]
I tried it again today after the latest update and all it does is hang my website, maybe I got the syntax wrong:

<enclosure url="http://podcdn.podbean.com/www.oldies104.net/'.$upload_dir.$singleFileName.'" length="'.$file_size.'" type="'.$filemimetype.'"/>
