### ISSUE TITLE
Missing artwork

### ISSUE THREAD

**Issue by soundneedle** [albertobeta/PodcastGenerator#87]
Probably my setup but I'm missing artwork when using Pocket Casts on android. All I've done in generator is replace the itunes image file with my own (keeping the file name unchanged). Is there other image files that might need to added? Don't think my MP3 files have embedded images, fyi.

I only have one "feed"---a daily radio show. Only need one image---but would like it to appear in any app, etc.

Thanks. Kinda new to this.

**Comment by albertobeta** [comment]
Does the artwork show in other podcast clients? If so it might be due to Pocket Cast (why not reaching out to them and aks?)
