### ISSUE TITLE
Add the "block" iTunes tag to the feed?

### ISSUE THREAD

**Issue by iamdadzilla** [albertobeta/PodcastGenerator#88]
Is there a way to add arbitrary tags at the podcast or episode level? I want to add the block tag (see [here](https://help.apple.com/itc/podcasts_connect/#/itcb54353390)).

**Comment by albertobeta** [comment]
hi! not yet implemented but you could try add it yourself by [tweaking this code](https://github.com/albertobeta/PodcastGenerator/blob/master/core/functions.php#L1195)
