### ISSUE TITLE
Unable to write permissions

### ISSUE THREAD

**Issue by jacobwoffenden** [albertobeta/PodcastGenerator#9]
I am trying to set up Podcast Generator with the following:
 - CentOS Linux release 7.1.1503 (Core)
 - PHP Version 5.4.16
 - NGINX 1.8.0

I tried to copy an existing version over from Ubuntu/Apache but get just a blank page when visiting the URL

I downloaded a fresh copy and followed the installation instructions as supplied on your website.
I receive the following on setup 
<img width="717" alt="screen shot 2015-07-24 at 16 13 22" src="https://cloud.githubusercontent.com/assets/9742606/8877764/0b2077d4-321f-11e5-97d6-4ead0fb69239.png">

This is the directory of the transferred copy (Blank in browser), as you can is 777

```
[root@server conf.d]# ll /var/www/podcast/
total 272
-rwxrwxrwx.  1 nginx nginx   169 Jul 24 15:35 categories.xml
drwxrwxrwx. 10 nginx nginx  4096 Jul 24 15:35 components
-rwxrwxrwx.  1 nginx nginx  3090 Jul 24 15:35 config.php
drwxrwxrwx.  3 nginx nginx  4096 Jul 24 15:35 core
-rwxrwxrwx.  1 nginx nginx  2254 Jul 24 15:35 download.php
-rwxrwxrwx.  1 nginx nginx 99678 Jul 24 15:35 favicon.ico
-rwxrwxrwx.  1 nginx nginx  4299 Jul 24 15:35 feed-icon.png
-rwxrwxrwx.  1 nginx nginx   769 Jul 24 15:35 feed.php
-rwxrwxrwx.  1 nginx nginx  3404 Jul 24 15:35 feed.xml
-rwxrwxrwx.  1 nginx nginx  1226 Jul 24 15:35 freebox-content.txt
-rwxrwxrwx.  1 nginx nginx 35146 Jul 24 15:35 GPL_license.txt
drwxrwxrwx.  2 nginx nginx    62 Jul 24 15:35 images
-rwxrwxrwx.  1 nginx nginx  4153 Jul 24 15:35 index.php
-rw-rw-rw-.  1 nginx nginx    20 Jul 24 15:54 info.php
-rwxrwxrwx.  1 nginx nginx 46963 Jul 24 15:35 loading.gif
drwxrwxrwx.  2 nginx nginx  4096 Jul 24 15:35 media
-rwxrwxrwx.  1 nginx nginx  3106 Jul 24 15:35 pg-cron.php
-rwxrwxrwx.  1 nginx nginx   253 Jul 24 15:35 podcast.gif
-rwxrwxrwx.  1 nginx nginx  1155 Jul 24 15:35 podcast_itunes.jpg
-rwxrwxrwx.  1 nginx nginx  3788 Jul 24 15:35 project-support.jpg
-rwxrwxrwx.  1 nginx nginx   119 Jul 24 15:35 rsscache_e1230b2b50361016f90defe167d7e02d
-rwxrwxrwx.  1 nginx nginx   214 Jul 24 15:35 rss-podcast.gif
drwxrwxrwx.  3 nginx nginx  4096 Jul 24 15:35 setup
drwxrwxrwx.  6 nginx nginx    95 Jul 24 15:35 themes
-rwxrwxrwx.  1 nginx nginx   534 Jul 24 15:35 video.png
```

**Comment by albertobeta** [comment]
Your user and group assigned to the directories images and media is nginx, but PG works as a web service and maybe the group assigned to the web services (e.g. "apache") cannot write into those directories (even though it's odd, since 777 should allow writing privileges to everyone in the system). Have you looked into that?

**Comment by jacobwoffenden** [comment]
I've tried changing to Apache and Root but nothing worked - Has it been tested with NGINX?

**Comment by albertobeta** [comment]
Personally, I tested PG just using Apache. Your problem is that you have a directory permission issue when writing directories or changing their persmission from a PHP script (maybe some security rule implementedd). You should look into that.

**Comment by jacobwoffenden** [comment]
It was SELinux - I've set it to permissive and it's now working.
