### ISSUE TITLE
install failed with error 

### ISSUE THREAD

**Issue by adamking904** [albertobeta/PodcastGenerator#92]
I am trying to install the files on my server. I upload unzip and go for location but only get white screen. I tried to manually visit mylocation/podcastgenerator/setup/index.php and step1.php. I have moved the files to diferent folder, but still same. Error code as follows. 

[19-Jul-2018 02:17:44 UTC] PHP Fatal error:  Call to undefined function mb_detect_encoding() in /home/public_html/PodcastGenerator/components/php-gettext/gettext.inc on line 177
Hoping someone has had the same issue or maybe knows a quick fix. thanks.

**Comment by Darkham42** [comment]
I was not able to install PG until I install php7.2-xml

I'm on Ubuntu with PHP and Nginx, if you too do : 
`apt install php7.2-xml`

Since it's install you'll be able to select the language at the first step and continue.
