### ISSUE TITLE
Podtrac tracking

### ISSUE THREAD

**Issue by velocipeter** [albertobeta/PodcastGenerator#94]
This isn't really an issue with PG. 
I followed the instructions from this page:http://www.podcastgenerator.net/documentation/FAQ-change-RSS-URL and there was no tracking. Podtrac wants the redirect to be part of the enclosure and when I followed this the main feed has the url, but not the specific enclosures within the feed itself.

Is there a way to get the "https://dts.podtrac.com/redirect.mp3" into each enclosure?

**Comment by webhelpus** [comment]
I had to edit the functions.php file on line 1384-1386

**Comment by velocipeter** [comment]
Yes, I got it to work, thank you. 
For others who might be having this problem. In the "core" folder there is a file called "functions.php". If you do a text  search for "enclosure" it will take you to line 1386 as stated above. There are a string of variables. I took out the $url tag and typed in the url with the podtrac information and it was working the next day.
