### ISSUE TITLE
Install Fail With Error (latest version:2.7)

### ISSUE THREAD

**Issue by JasonGrass** [albertobeta/PodcastGenerator#95]
PHP Warning: include(config.php): failed to open stream: No such file or directory in C:\web\podcast\core\includes.php on line 20 
PHP Warning: include(): Failed opening 'config.php' for inclusion (include_path='.;C:\php\pear') in C:\web\podcast\core\includes.php on line 20 
PHP Notice: Undefined variable: absoluteurl in C:\web\podcast\core\includes.php on line 22 
PHP Notice: Undefined variable: absoluteurl in C:\web\podcast\core\includes.php on line 24 
PHP Notice: Undefined variable: absoluteurl in C:\web\podcast\core\language.php on line 38 
PHP Notice: Undefined variable: absoluteurl in C:\web\podcast\core\language.php on line 64 
PHP Warning: include(config.php): failed to open stream: No such file or directory in C:\web\podcast\core\includes.php on line 20 
PHP Warning: include(): Failed opening 'config.php' for inclusion (include_path='.;C:\php\pear') in C:\web\podcast\core\includes.php on line 20 
HP Notice: Undefined variable: absoluteurl in C:\web\podcast\core\includes.php on line 22 
PHP Notice: Undefined variable: absoluteurl in C:\web\podcast\core\includes.php on line 24

**Comment by minidfx** [comment]
Almost pretty sure this is a duplicate issue with this one: https://github.com/albertobeta/PodcastGenerator/issues/21
