### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Darkham42** [albertobeta/PodcastGenerator#96]
Hey ! During the installation I've change the language but it's still in english...

If I remove all local folders it's changing nothing it's still in english but files are moved so it can't be in english O.o

Any idea ?

**Comment by albertobeta** [comment]
yes, it's related to the GETTEXT extension in PHP. Is it enabled, if so try to disable it. In case it is disabled... well try the opposite and enable it.
PG uses [gettext](https://www.gnu.org/software/gettext/) to handle localization. When gettext is not installed as an extension in PHP, PG relies on a third party implementation ([php-gettext](https://launchpad.net/php-gettext/)). In some server setups the native PHP extension doesn't work well with PG, hence why I am suggesting to play with that parameter in your PHP configuration.

**Comment by Darkham42** [comment]
Thanks @albertobeta I'll take a look as soon as I can.

**Comment by douglaszarruda** [comment]
I had the same issue here. I'm on Ubuntu 18.04.1 and PHP 7.2
I removed the following line in /etc/php/7.2/mods-available/gettext.ini and it worked, now it's translating properly

> extension=gettext.so

**Comment by Darkham42** [comment]
It's works great @douglaszarruda !
Thanks :)
