### ISSUE TITLE
Upload Podcast Error: No file, description or title present 

### ISSUE THREAD

**Issue by KMDee** [albertobeta/PodcastGenerator#97]
Not sure if i have something set up wrong or if i need to configure permissions. Please help!
thanks.

**Comment by albertobeta** [comment]
Given the error, it´s probably a permission issue. Just to make sure, set permission 777 for the media folder and see if it works. See [the list of files and folders that need full read/write permission for the web-user](http://www.podcastgenerator.net/documentation/upgrade).

**Comment by KMDee** [comment]
Thank you. I will try that and let you know if it worked.

**Comment by KMDee** [comment]
Hi Albert -- Opened permissions, same errors and I keep trying to do the
indexing. Can you help me understand how the two need to connect or if the
system is looking for a specifically named folder?

**Comment by pettedemon** [comment]
Hi,
I have the same problem with php 7
